"""Add Member model and User/Unit relationships

Revision ID: 00356b81d8f9
Revises: 34b6a69cb6a5
Create Date: 2025-07-20 16:15:23.418898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00356b81d8f9'
down_revision = '34b6a69cb6a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_column('ai_source_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_source_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
