"""Add ContractorFeedback Table

Revision ID: 05e290ba2958
Revises: c7a3161f79c1
Create Date: 2025-07-15 16:39:30.272827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05e290ba2958'
down_revision = 'c7a3161f79c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contractor_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contractor_id', sa.Integer(), nullable=False),
    sa.Column('given_by_id', sa.Integer(), nullable=False),
    sa.Column('overall_rating', sa.Float(), nullable=False),
    sa.Column('punctuality', sa.Float(), nullable=True),
    sa.Column('quality_of_work', sa.Float(), nullable=True),
    sa.Column('communication', sa.Float(), nullable=True),
    sa.Column('professionalism', sa.Float(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_anonymous', sa.Boolean(), nullable=True),
    sa.Column('visibility_scope', sa.String(length=100), nullable=True),
    sa.Column('consent_verified', sa.Boolean(), nullable=True),
    sa.Column('feedback_source', sa.String(length=50), nullable=True),
    sa.Column('external_reference', sa.String(length=100), nullable=True),
    sa.Column('source_system', sa.String(length=100), nullable=True),
    sa.Column('is_external', sa.Boolean(), nullable=True),
    sa.Column('parsed_summary', sa.Text(), nullable=True),
    sa.Column('gar_sentiment_score', sa.Float(), nullable=True),
    sa.Column('gar_flagged_language', sa.Boolean(), nullable=True),
    sa.Column('gar_recommendation', sa.String(length=255), nullable=True),
    sa.Column('gar_explanation', sa.Text(), nullable=True),
    sa.Column('tone_classification', sa.String(length=50), nullable=True),
    sa.Column('feedback_quality_score', sa.Float(), nullable=True),
    sa.Column('parsed_by_ai_version', sa.String(length=50), nullable=True),
    sa.Column('parsed_at', sa.DateTime(), nullable=True),
    sa.Column('is_ai_processed', sa.Boolean(), nullable=True),
    sa.Column('ai_profile_locked', sa.Boolean(), nullable=True),
    sa.Column('gar_chat_ready', sa.Boolean(), nullable=True),
    sa.Column('gar_feedback', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], ),
    sa.ForeignKeyConstraint(['given_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contractor_feedback')
    # ### end Alembic commands ###
