"""Add media_files table

Revision ID: 062ae58f853b
Revises: 24a86983e3cb
Create Date: 2025-07-12 16:59:06.304484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '062ae58f853b'
down_revision = '24a86983e3cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=200), nullable=False),
    sa.Column('file_path', sa.String(length=250), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('related_table', sa.String(length=50), nullable=False),
    sa.Column('related_id', sa.Integer(), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.Column('visibility', sa.String(length=20), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('parsed_summary', sa.Text(), nullable=True),
    sa.Column('extracted_data', sa.JSON(), nullable=True),
    sa.Column('parsing_status', sa.String(length=50), nullable=True),
    sa.Column('parsed_at', sa.DateTime(), nullable=True),
    sa.Column('parsed_by_ai_version', sa.String(length=50), nullable=True),
    sa.Column('ai_source_type', sa.String(length=50), nullable=True),
    sa.Column('is_ai_processed', sa.Boolean(), nullable=True),
    sa.Column('ai_classification', sa.String(length=100), nullable=True),
    sa.Column('ai_confidence_score', sa.Float(), nullable=True),
    sa.Column('ai_detected_issues', sa.Text(), nullable=True),
    sa.Column('ai_recommendations', sa.Text(), nullable=True),
    sa.Column('ai_scorecard', sa.JSON(), nullable=True),
    sa.Column('ai_rank', sa.String(length=20), nullable=True),
    sa.Column('is_ai_preferred', sa.Boolean(), nullable=True),
    sa.Column('reason_for_recommendation', sa.Text(), nullable=True),
    sa.Column('tags', sa.String(length=255), nullable=True),
    sa.Column('role_visibility', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('media_files')
    # ### end Alembic commands ###
