"""Update WorkOrder Table

Revision ID: 06b1205c7beb
Revises: b68cee374e6e
Create Date: 2025-07-19 08:18:30.388181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06b1205c7beb'
down_revision = 'b68cee374e6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_order_completions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('confirmed_by_admin_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['assigned_user_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['confirmed_by_admin_id'], ['id'])

    with op.batch_alter_table('work_order_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allow_assign_to_staff', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('allow_assign_to_team', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('restrict_completion_to_assigned', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('require_admin_confirmation_for_completion', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('allow_staff_self_acceptance', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_order_settings', schema=None) as batch_op:
        batch_op.drop_column('allow_staff_self_acceptance')
        batch_op.drop_column('require_admin_confirmation_for_completion')
        batch_op.drop_column('restrict_completion_to_assigned')
        batch_op.drop_column('allow_assign_to_team')
        batch_op.drop_column('allow_assign_to_staff')

    with op.batch_alter_table('work_order_completions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('confirmed_by_admin_id')
        batch_op.drop_column('assigned_user_id')

    # ### end Alembic commands ###
