"""Create accounts table

Revision ID: 07f7d2b8e5b1
Revises: 3e08a466b876
Create Date: 2025-07-13 12:59:44.994296

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '07f7d2b8e5b1'
down_revision = '3e08a466b876'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('finance_batch_id', sa.Integer(), nullable=True),
    sa.Column('account_name', sa.String(length=150), nullable=False),
    sa.Column('account_type', sa.String(length=50), nullable=False),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('access_level', sa.String(length=50), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('last_modified_by_id', sa.Integer(), nullable=True),
    sa.Column('parsed_text', sa.Text(), nullable=True),
    sa.Column('parsed_summary', sa.Text(), nullable=True),
    sa.Column('extracted_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_scorecard', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_flagged', sa.Boolean(), nullable=True),
    sa.Column('gar_context_reference', sa.String(length=255), nullable=True),
    sa.Column('gar_recommendation', sa.String(length=255), nullable=True),
    sa.Column('gar_risk_rating', sa.String(length=50), nullable=True),
    sa.Column('flagged_reason', sa.Text(), nullable=True),
    sa.Column('gar_chat_ready', sa.Boolean(), nullable=True),
    sa.Column('gar_feedback', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['finance_batch_id'], ['finance_batches.id'], ),
    sa.ForeignKeyConstraint(['last_modified_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reconciliation_batch_id', sa.String(length=100), nullable=True))

    with op.batch_alter_table('service_charges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reconciliation_batch_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'reconciliation_batches', ['reconciliation_batch_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_charges', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('reconciliation_batch_id')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('reconciliation_batch_id')

    op.drop_table('accounts')
    # ### end Alembic commands ###
