"""Add AccessLog Table

Revision ID: 098b84aeff1e
Revises: 221cf6e8f51f
Create Date: 2025-07-15 21:14:19.589217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '098b84aeff1e'
down_revision = '221cf6e8f51f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('access_type', sa.String(length=100), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('device_info', sa.String(length=255), nullable=True),
    sa.Column('geo_location', sa.String(length=100), nullable=True),
    sa.Column('accessed_at', sa.DateTime(), nullable=True),
    sa.Column('privacy_scope', sa.String(length=100), nullable=True),
    sa.Column('access_masked', sa.Boolean(), nullable=True),
    sa.Column('external_reference', sa.String(length=100), nullable=True),
    sa.Column('source_system', sa.String(length=100), nullable=True),
    sa.Column('is_external', sa.Boolean(), nullable=True),
    sa.Column('parsed_context', sa.JSON(), nullable=True),
    sa.Column('parsed_by_ai_version', sa.String(length=50), nullable=True),
    sa.Column('gar_access_risk_score', sa.Float(), nullable=True),
    sa.Column('gar_explanation', sa.Text(), nullable=True),
    sa.Column('gar_flagged_event', sa.Boolean(), nullable=True),
    sa.Column('gar_chat_ready', sa.Boolean(), nullable=True),
    sa.Column('gar_feedback', sa.Text(), nullable=True),
    sa.Column('is_ai_processed', sa.Boolean(), nullable=True),
    sa.Column('ai_profile_locked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('access_logs')
    # ### end Alembic commands ###
