"""add key site info tables

Revision ID: 0a28aae01e8f
Revises: 52c3a07899f5
Create Date: 2025-10-03 21:25:33.926826

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0a28aae01e8f'
down_revision = '52c3a07899f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_key_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('active', 'archived', name='key_info_status'), nullable=False),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_submitted_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ai_parsed_text', sa.Text(), nullable=True),
    sa.Column('ai_parsed_summary', sa.String(length=1000), nullable=True),
    sa.Column('ai_extracted_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ai_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ai_redaction_hints', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ai_visibility_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ai_scorecard', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ai_rank', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['last_submitted_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'title', name='uq_client_key_info_client_title')
    )
    with op.batch_alter_table('client_key_info', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_key_info_client_id'), ['client_id'], unique=False)
        batch_op.create_index('ix_client_key_info_client_status', ['client_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_key_info_title'), ['title'], unique=False)

    op.create_table('client_key_info_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('key_info_id', sa.Integer(), nullable=True),
    sa.Column('proposed_title', sa.String(length=160), nullable=False),
    sa.Column('proposed_content', sa.Text(), nullable=False),
    sa.Column('proposed_contractor_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pro_attested_by_contractor', sa.Boolean(), nullable=False),
    sa.Column('pro_attestation_note', sa.String(length=500), nullable=True),
    sa.Column('submitted_by_id', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='key_info_change_status'), nullable=False),
    sa.Column('decided_by_id', sa.Integer(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_reason', sa.String(length=300), nullable=True),
    sa.Column('ai_parsed_text', sa.Text(), nullable=True),
    sa.Column('ai_parsed_summary', sa.String(length=1000), nullable=True),
    sa.Column('ai_extracted_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ai_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ai_redaction_hints', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ai_visibility_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ai_scorecard', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ai_rank', sa.Integer(), nullable=True),
    sa.CheckConstraint("status IN ('pending','approved','rejected')", name='ck_key_info_changes_status_valid'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['decided_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['key_info_id'], ['client_key_info.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client_key_info_changes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_key_info_changes_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_key_info_changes_key_info_id'), ['key_info_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_key_info_changes_status'), ['status'], unique=False)
        batch_op.create_index('ix_key_info_changes_client_status', ['client_id', 'status'], unique=False)

    op.create_table('client_key_info_shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key_info_id', sa.Integer(), nullable=False),
    sa.Column('contractor_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['key_info_id'], ['client_key_info.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_info_id', 'contractor_id', name='uq_key_info_share_unique')
    )
    with op.batch_alter_table('client_key_info_shares', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_key_info_shares_contractor_id'), ['contractor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_key_info_shares_key_info_id'), ['key_info_id'], unique=False)
        batch_op.create_index('ix_key_info_share_key_info_contractor', ['key_info_id', 'contractor_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_key_info_shares', schema=None) as batch_op:
        batch_op.drop_index('ix_key_info_share_key_info_contractor')
        batch_op.drop_index(batch_op.f('ix_client_key_info_shares_key_info_id'))
        batch_op.drop_index(batch_op.f('ix_client_key_info_shares_contractor_id'))

    op.drop_table('client_key_info_shares')
    with op.batch_alter_table('client_key_info_changes', schema=None) as batch_op:
        batch_op.drop_index('ix_key_info_changes_client_status')
        batch_op.drop_index(batch_op.f('ix_client_key_info_changes_status'))
        batch_op.drop_index(batch_op.f('ix_client_key_info_changes_key_info_id'))
        batch_op.drop_index(batch_op.f('ix_client_key_info_changes_client_id'))

    op.drop_table('client_key_info_changes')
    with op.batch_alter_table('client_key_info', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_key_info_title'))
        batch_op.drop_index('ix_client_key_info_client_status')
        batch_op.drop_index(batch_op.f('ix_client_key_info_client_id'))

    op.drop_table('client_key_info')
    # ### end Alembic commands ###
