"""Add LoanStatement model

Revision ID: 0be5dd887ded
Revises: 1e8606c5f569
Create Date: 2025-07-14 21:36:38.597897

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0be5dd887ded'
down_revision = '1e8606c5f569'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loan_statements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('entry_date', sa.DateTime(), nullable=True),
    sa.Column('transaction_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('is_reconciled', sa.Boolean(), nullable=True),
    sa.Column('is_reversal', sa.Boolean(), nullable=True),
    sa.Column('linked_payment_id', sa.Integer(), nullable=True),
    sa.Column('external_reference_id', sa.String(length=255), nullable=True),
    sa.Column('integration_source', sa.String(length=100), nullable=True),
    sa.Column('sync_status', sa.String(length=50), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.Column('ai_tag', sa.String(length=100), nullable=True),
    sa.Column('gar_flagged', sa.Boolean(), nullable=True),
    sa.Column('gar_context_reference', sa.String(length=100), nullable=True),
    sa.Column('ai_notes', sa.Text(), nullable=True),
    sa.Column('extracted_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_modified_at', sa.DateTime(), nullable=True),
    sa.Column('last_modified_by_id', sa.Integer(), nullable=True),
    sa.Column('ip_logged_from', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['last_modified_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['linked_payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loan_statements')
    # ### end Alembic commands ###
