"""Update User model with GAR AI and quoting relationships

Revision ID: 14129806d28c
Revises: 098b84aeff1e
Create Date: 2025-07-15 21:20:31.332112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14129806d28c'
down_revision = '098b84aeff1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'contractors', ['contractor_id'], ['id'])
        batch_op.create_foreign_key(None, 'roles', ['role_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
