"""Add UnitMembership join model for unit-member timelines

Revision ID: 1c51c8e7f8e0
Revises: 0a28aae01e8f
Create Date: 2025-12-04 08:33:47.017961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c51c8e7f8e0'
down_revision = '0a28aae01e8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('building_type', sa.String(length=50), nullable=True),
    sa.Column('number_of_cores', sa.Integer(), nullable=True),
    sa.Column('number_of_floors', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('lift_count', sa.Integer(), nullable=True),
    sa.Column('stair_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unit_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('ownership_start_date', sa.Date(), nullable=True),
    sa.Column('ownership_end_date', sa.Date(), nullable=True),
    sa.Column('tenancy_start_date', sa.Date(), nullable=True),
    sa.Column('tenancy_end_date', sa.Date(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('gar_flags', sa.Text(), nullable=True),
    sa.Column('gar_score', sa.Float(), nullable=True),
    sa.Column('gar_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('unit_memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_unit_memberships_is_current'), ['is_current'], unique=False)
        batch_op.create_index(batch_op.f('ix_unit_memberships_member_id'), ['member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_unit_memberships_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_unit_memberships_unit_id'), ['unit_id'], unique=False)

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'units', ['unit_id'], ['id'])

    with op.batch_alter_table('member_units', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ownership_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('purchase_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('sale_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('tenancy_start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('tenancy_end_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('tenancy_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('is_primary_residence', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_landlord', sa.Boolean(), nullable=True))

    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('salutation', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('first_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('alternate_phone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('postal_address_line1', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('postal_address_line2', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('postal_city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('postal_region', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('postal_postcode', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('postal_country', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('is_owner', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_director', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_company_representative', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_owner_occupier', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('preferred_contact_method', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('source_system',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'clients', ['client_id'], ['id'])
        batch_op.create_foreign_key(None, 'companies', ['company_id'], ['id'])

    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.add_column(sa.Column('block_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('core_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('parent_unit_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('unit_reference', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('unit_category', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('address_line_2', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('town_city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('county_region', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('bedrooms', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bathrooms', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('parking_label', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('storage_label', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('electricity_mprn', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('gas_mprn', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('water_meter_reference', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('finance_ledger_code', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('finance_external_ref', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('lease_term_years', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('lease_reference', sa.String(length=100), nullable=True))
        batch_op.drop_constraint('units_tenant_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('units_client_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('units_company_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('units_resident_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'cores', ['core_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'clients', ['client_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'companies', ['company_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'units', ['parent_unit_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'blocks', ['block_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('resident_id')
        batch_op.drop_column('tenant_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('resident_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('units_resident_id_fkey', 'users', ['resident_id'], ['id'])
        batch_op.create_foreign_key('units_company_id_fkey', 'companies', ['company_id'], ['id'])
        batch_op.create_foreign_key('units_client_id_fkey', 'clients', ['client_id'], ['id'])
        batch_op.create_foreign_key('units_tenant_id_fkey', 'users', ['tenant_id'], ['id'])
        batch_op.drop_column('lease_reference')
        batch_op.drop_column('lease_term_years')
        batch_op.drop_column('finance_external_ref')
        batch_op.drop_column('finance_ledger_code')
        batch_op.drop_column('water_meter_reference')
        batch_op.drop_column('gas_mprn')
        batch_op.drop_column('electricity_mprn')
        batch_op.drop_column('storage_label')
        batch_op.drop_column('parking_label')
        batch_op.drop_column('bathrooms')
        batch_op.drop_column('bedrooms')
        batch_op.drop_column('country')
        batch_op.drop_column('county_region')
        batch_op.drop_column('town_city')
        batch_op.drop_column('address_line_2')
        batch_op.drop_column('unit_category')
        batch_op.drop_column('unit_reference')
        batch_op.drop_column('parent_unit_id')
        batch_op.drop_column('core_id')
        batch_op.drop_column('block_id')

    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('source_system',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('preferred_contact_method')
        batch_op.drop_column('is_active')
        batch_op.drop_column('is_owner_occupier')
        batch_op.drop_column('is_company_representative')
        batch_op.drop_column('is_director')
        batch_op.drop_column('is_owner')
        batch_op.drop_column('postal_country')
        batch_op.drop_column('postal_postcode')
        batch_op.drop_column('postal_region')
        batch_op.drop_column('postal_city')
        batch_op.drop_column('postal_address_line2')
        batch_op.drop_column('postal_address_line1')
        batch_op.drop_column('alternate_phone')
        batch_op.drop_column('phone')
        batch_op.drop_column('email')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')
        batch_op.drop_column('salutation')
        batch_op.drop_column('company_id')
        batch_op.drop_column('client_id')

    with op.batch_alter_table('member_units', schema=None) as batch_op:
        batch_op.drop_column('is_landlord')
        batch_op.drop_column('is_primary_residence')
        batch_op.drop_column('tenancy_status')
        batch_op.drop_column('tenancy_end_date')
        batch_op.drop_column('tenancy_start_date')
        batch_op.drop_column('sale_date')
        batch_op.drop_column('purchase_date')
        batch_op.drop_column('ownership_type')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('unit_id')

    with op.batch_alter_table('unit_memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_unit_memberships_unit_id'))
        batch_op.drop_index(batch_op.f('ix_unit_memberships_role'))
        batch_op.drop_index(batch_op.f('ix_unit_memberships_member_id'))
        batch_op.drop_index(batch_op.f('ix_unit_memberships_is_current'))

    op.drop_table('unit_memberships')
    op.drop_table('cores')
    op.drop_table('blocks')
    # ### end Alembic commands ###
