"""Add Loan model

Revision ID: 1e8606c5f569
Revises: 4285910e4af5
Create Date: 2025-07-14 21:35:20.362181

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1e8606c5f569'
down_revision = '4285910e4af5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('lender_name', sa.String(length=255), nullable=False),
    sa.Column('loan_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('interest_rate', sa.Float(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('repayment_frequency', sa.String(length=50), nullable=True),
    sa.Column('repayment_method', sa.String(length=50), nullable=True),
    sa.Column('is_interest_only', sa.Boolean(), nullable=True),
    sa.Column('balloon_payment_due', sa.Boolean(), nullable=True),
    sa.Column('grace_period_months', sa.Integer(), nullable=True),
    sa.Column('contract_reference', sa.String(length=100), nullable=True),
    sa.Column('supporting_document_url', sa.String(length=255), nullable=True),
    sa.Column('terms_summary', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('ai_tag', sa.String(length=100), nullable=True),
    sa.Column('parsed_summary', sa.Text(), nullable=True),
    sa.Column('extracted_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('gar_risk_flag', sa.Boolean(), nullable=True),
    sa.Column('gar_risk_rating', sa.String(length=50), nullable=True),
    sa.Column('gar_recommendations', sa.Text(), nullable=True),
    sa.Column('gar_context_reference', sa.String(length=100), nullable=True),
    sa.Column('external_loan_id', sa.String(length=100), nullable=True),
    sa.Column('external_provider', sa.String(length=100), nullable=True),
    sa.Column('integration_status', sa.String(length=50), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('ip_created_from', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loans')
    # ### end Alembic commands ###
