"""Add AGMParticipant table

Revision ID: 1fb4d5e49055
Revises: 89e534a13561
Create Date: 2025-07-14 22:32:49.647215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fb4d5e49055'
down_revision = '89e534a13561'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agm_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agm_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('represented_by_id', sa.Integer(), nullable=True),
    sa.Column('attended', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('attendance_status', sa.String(length=50), nullable=True),
    sa.Column('vote_cast', sa.JSON(), nullable=True),
    sa.Column('vote_timestamp', sa.DateTime(), nullable=True),
    sa.Column('gar_flagged_issues', sa.Text(), nullable=True),
    sa.Column('gar_confidence_score', sa.Float(), nullable=True),
    sa.Column('gar_chat_ready', sa.Boolean(), nullable=True),
    sa.Column('gar_feedback', sa.Text(), nullable=True),
    sa.Column('gar_resolution_status', sa.String(length=50), nullable=True),
    sa.Column('visibility_roles', sa.String(length=255), nullable=True),
    sa.Column('tags', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['agm_id'], ['agms.id'], ),
    sa.ForeignKeyConstraint(['represented_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agm_participants')
    # ### end Alembic commands ###
