"""Add inspection_schedules table

Revision ID: 24a86983e3cb
Revises: 4aa279a1eace
Create Date: 2025-07-12 16:56:29.668337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24a86983e3cb'
down_revision = '4aa279a1eace'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inspection_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('frequency', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('next_due_date', sa.Date(), nullable=True),
    sa.Column('last_inspection_date', sa.Date(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('ai_parsed_summary', sa.Text(), nullable=True),
    sa.Column('extracted_data', sa.JSON(), nullable=True),
    sa.Column('parsing_status', sa.String(length=50), nullable=True),
    sa.Column('parsed_by_ai_version', sa.String(length=50), nullable=True),
    sa.Column('parsed_at', sa.DateTime(), nullable=True),
    sa.Column('ai_source_type', sa.String(length=50), nullable=True),
    sa.Column('is_ai_processed', sa.Boolean(), nullable=True),
    sa.Column('ai_profile_locked', sa.Boolean(), nullable=True),
    sa.Column('ai_scheduling_risk', sa.Text(), nullable=True),
    sa.Column('ai_recommended_frequency', sa.String(length=50), nullable=True),
    sa.Column('ai_alignment_score', sa.Float(), nullable=True),
    sa.Column('gar_notes', sa.Text(), nullable=True),
    sa.Column('gar_chat_ready', sa.Boolean(), nullable=True),
    sa.Column('gar_feedback', sa.Text(), nullable=True),
    sa.Column('visibility_scope', sa.String(length=100), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=True),
    sa.Column('shared_with_director', sa.Boolean(), nullable=True),
    sa.Column('consent_verified', sa.Boolean(), nullable=True),
    sa.Column('external_reference', sa.String(length=100), nullable=True),
    sa.Column('source_system', sa.String(length=100), nullable=True),
    sa.Column('is_external', sa.Boolean(), nullable=True),
    sa.Column('sync_status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inspection_schedules')
    # ### end Alembic commands ###
