"""Add WorkOrder Table

Revision ID: 26a7bbc7046b
Revises: 05e290ba2958
Create Date: 2025-07-15 20:21:09.814946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26a7bbc7046b'
down_revision = '05e290ba2958'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contractor_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('request_type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('business_type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('occupant_name', sa.String(length=100), nullable=True),
    sa.Column('occupant_apartment', sa.String(length=50), nullable=True),
    sa.Column('occupant_phone', sa.String(length=20), nullable=True),
    sa.Column('privacy_scope', sa.String(length=100), nullable=True),
    sa.Column('access_masked', sa.Boolean(), nullable=True),
    sa.Column('preferred_visit_date', sa.Date(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('preferred_contractor_id', sa.Integer(), nullable=True),
    sa.Column('second_preferred_contractor_id', sa.Integer(), nullable=True),
    sa.Column('accepted_contractor_id', sa.Integer(), nullable=True),
    sa.Column('quote_requested', sa.Boolean(), nullable=True),
    sa.Column('quote_deadline', sa.DateTime(), nullable=True),
    sa.Column('quote_status', sa.String(length=50), nullable=True),
    sa.Column('quote_approved_by_id', sa.Integer(), nullable=True),
    sa.Column('quote_approved_at', sa.DateTime(), nullable=True),
    sa.Column('converted_to_work_order', sa.Boolean(), nullable=True),
    sa.Column('alert_id', sa.Integer(), nullable=True),
    sa.Column('escalated_by_id', sa.Integer(), nullable=True),
    sa.Column('external_reference', sa.String(length=100), nullable=True),
    sa.Column('source_system', sa.String(length=100), nullable=True),
    sa.Column('is_external', sa.Boolean(), nullable=True),
    sa.Column('is_imported', sa.Boolean(), nullable=True),
    sa.Column('geo_location', sa.String(length=100), nullable=True),
    sa.Column('attachments_count', sa.Integer(), nullable=True),
    sa.Column('parsed_summary', sa.Text(), nullable=True),
    sa.Column('extracted_data', sa.JSON(), nullable=True),
    sa.Column('parsing_status', sa.String(length=50), nullable=True),
    sa.Column('parsed_at', sa.DateTime(), nullable=True),
    sa.Column('parsed_by_ai_version', sa.String(length=50), nullable=True),
    sa.Column('ai_source_type', sa.String(length=50), nullable=True),
    sa.Column('is_ai_processed', sa.Boolean(), nullable=True),
    sa.Column('ai_profile_locked', sa.Boolean(), nullable=True),
    sa.Column('ai_field_ranking', sa.JSON(), nullable=True),
    sa.Column('gar_risk_level', sa.String(length=50), nullable=True),
    sa.Column('gar_urgency_score', sa.Float(), nullable=True),
    sa.Column('gar_non_compliance_notes', sa.Text(), nullable=True),
    sa.Column('gar_flagged', sa.Boolean(), nullable=True),
    sa.Column('gar_recommended_action', sa.String(length=255), nullable=True),
    sa.Column('gar_alignment_score', sa.Float(), nullable=True),
    sa.Column('gar_explanation', sa.Text(), nullable=True),
    sa.Column('gar_chat_ready', sa.Boolean(), nullable=True),
    sa.Column('gar_feedback', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['accepted_contractor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['escalated_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['preferred_contractor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['quote_approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['second_preferred_contractor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_orders')
    # ### end Alembic commands ###
