"""Add TrialBalance table

Revision ID: 28f1ba6dd6f6
Revises: 64bfee80676a
Create Date: 2025-07-13 14:26:56.956949

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '28f1ba6dd6f6'
down_revision = '64bfee80676a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trial_balances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('total_debits', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_credits', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('is_balanced', sa.Boolean(), nullable=True),
    sa.Column('account_summaries', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parsed_text', sa.Text(), nullable=True),
    sa.Column('extracted_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('gar_score', sa.String(length=20), nullable=True),
    sa.Column('gar_flag', sa.String(length=255), nullable=True),
    sa.Column('gar_recommendation', sa.Text(), nullable=True),
    sa.Column('gar_context_reference', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batch_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_journal_entries_batch_id'), ['batch_id'], unique=False)
        batch_op.create_foreign_key(None, 'journal_batches', ['batch_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_journal_entries_batch_id'))
        batch_op.drop_column('batch_id')

    op.drop_table('trial_balances')
    # ### end Alembic commands ###
