"""Add LateFeeInterestPolicy model

Revision ID: 2933e6b3a913
Revises: c7830243c89d
Create Date: 2025-07-14 21:44:03.541722

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2933e6b3a913'
down_revision = 'c7830243c89d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('late_fee_interest_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('applies_to', sa.String(length=50), nullable=False),
    sa.Column('area_type_id', sa.Integer(), nullable=True),
    sa.Column('grace_period_days', sa.Integer(), nullable=True),
    sa.Column('fixed_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('interest_rate_percent', sa.Float(), nullable=True),
    sa.Column('interest_frequency', sa.String(length=50), nullable=True),
    sa.Column('compound_interest', sa.Boolean(), nullable=True),
    sa.Column('maximum_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('min_fee_trigger_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('lease_clause_reference', sa.String(length=100), nullable=True),
    sa.Column('lease_clause_text', sa.Text(), nullable=True),
    sa.Column('parsed_summary', sa.Text(), nullable=True),
    sa.Column('parsed_text', sa.Text(), nullable=True),
    sa.Column('ai_tags', sa.Text(), nullable=True),
    sa.Column('ai_scorecard', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extracted_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('gar_risk_flag', sa.Boolean(), nullable=True),
    sa.Column('context_tags', sa.ARRAY(sa.String(length=50)), nullable=True),
    sa.Column('role_visibility', sa.ARRAY(sa.String(length=50)), nullable=True),
    sa.Column('gar_chat_ready', sa.Boolean(), nullable=True),
    sa.Column('gar_feedback', sa.Text(), nullable=True),
    sa.Column('external_reference', sa.String(length=100), nullable=True),
    sa.Column('external_system', sa.String(length=100), nullable=True),
    sa.Column('sync_status', sa.String(length=50), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['area_type_id'], ['area_types.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('late_fee_interest_policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_late_fee_interest_policies_applies_to'), ['applies_to'], unique=False)
        batch_op.create_index(batch_op.f('ix_late_fee_interest_policies_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_late_fee_interest_policies_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_late_fee_interest_policies_effective_date'), ['effective_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('late_fee_interest_policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_late_fee_interest_policies_effective_date'))
        batch_op.drop_index(batch_op.f('ix_late_fee_interest_policies_company_id'))
        batch_op.drop_index(batch_op.f('ix_late_fee_interest_policies_client_id'))
        batch_op.drop_index(batch_op.f('ix_late_fee_interest_policies_applies_to'))

    op.drop_table('late_fee_interest_policies')
    # ### end Alembic commands ###
