"""add unit generation fields

Revision ID: 2d7f3a9c5b61
Revises: 1c51c8e7f8e0
Create Date: 2026-05-16 10:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


revision = "2d7f3a9c5b61"
down_revision = "1c51c8e7f8e0"
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table("clients", schema=None) as batch_op:
        batch_op.add_column(sa.Column("units_other", sa.Integer(), nullable=True, server_default="0"))

    with op.batch_alter_table("units", schema=None) as batch_op:
        batch_op.add_column(sa.Column("unit_number", sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column("unit_name", sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column("core_name", sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column("area_name", sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column("entrance", sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column("status", sa.String(length=50), nullable=False, server_default="Active"))
        batch_op.add_column(sa.Column("autogenerated", sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column("is_common_area", sa.Boolean(), nullable=True, server_default=sa.false()))
        batch_op.create_unique_constraint(
            "uq_units_client_block_type_number",
            ["client_id", "block_name", "unit_type", "unit_number"],
        )

    with op.batch_alter_table("clients", schema=None) as batch_op:
        batch_op.alter_column("units_other", server_default=None)

    with op.batch_alter_table("units", schema=None) as batch_op:
        batch_op.alter_column("status", server_default=None)
        batch_op.alter_column("autogenerated", server_default=None)
        batch_op.alter_column("is_common_area", server_default=None)


def downgrade():
    with op.batch_alter_table("units", schema=None) as batch_op:
        batch_op.drop_constraint("uq_units_client_block_type_number", type_="unique")
        batch_op.drop_column("is_common_area")
        batch_op.drop_column("autogenerated")
        batch_op.drop_column("status")
        batch_op.drop_column("entrance")
        batch_op.drop_column("area_name")
        batch_op.drop_column("core_name")
        batch_op.drop_column("unit_name")
        batch_op.drop_column("unit_number")

    with op.batch_alter_table("clients", schema=None) as batch_op:
        batch_op.drop_column("units_other")
