"""Fix ambiguous foreign keys in Inspection

Revision ID: 30ac4ab32714
Revises: 00356b81d8f9
Create Date: 2025-07-20 17:43:15.811937

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '30ac4ab32714'
down_revision = '00356b81d8f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspections', schema=None) as batch_op:
        batch_op.drop_column('reviewed_at')
        batch_op.drop_column('review_notes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review_notes', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('reviewed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
