"""Add Lease table

Revision ID: 34da33174acd
Revises: 5a9d66d0eae1
Create Date: 2025-07-14 22:25:56.238656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34da33174acd'
down_revision = '5a9d66d0eae1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('country_config_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('lease_type', sa.String(length=50), nullable=True),
    sa.Column('lease_status', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('renewal_terms', sa.Text(), nullable=True),
    sa.Column('auto_renew_enabled', sa.Boolean(), nullable=True),
    sa.Column('notice_period_days', sa.Integer(), nullable=True),
    sa.Column('rent_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('rent_currency', sa.String(length=10), nullable=True),
    sa.Column('billing_cycle', sa.String(length=50), nullable=True),
    sa.Column('service_charge_contribution', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('late_payment_penalty', sa.String(length=100), nullable=True),
    sa.Column('permitted_use', sa.String(length=255), nullable=True),
    sa.Column('rent_review_frequency', sa.String(length=50), nullable=True),
    sa.Column('break_clause', sa.String(length=255), nullable=True),
    sa.Column('insurance_requirements', sa.Text(), nullable=True),
    sa.Column('common_area_usage_terms', sa.Text(), nullable=True),
    sa.Column('document_filename', sa.String(length=255), nullable=True),
    sa.Column('document_path', sa.String(length=255), nullable=True),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.Column('parsed_summary', sa.Text(), nullable=True),
    sa.Column('extracted_data', sa.JSON(), nullable=True),
    sa.Column('parsing_status', sa.String(length=50), nullable=True),
    sa.Column('parsed_at', sa.DateTime(), nullable=True),
    sa.Column('parsed_by_ai_version', sa.String(length=50), nullable=True),
    sa.Column('ai_source_type', sa.String(length=50), nullable=True),
    sa.Column('is_ai_processed', sa.Boolean(), nullable=True),
    sa.Column('gar_compliance_score', sa.Float(), nullable=True),
    sa.Column('gar_flagged_issues', sa.Text(), nullable=True),
    sa.Column('gar_key_clauses', sa.JSON(), nullable=True),
    sa.Column('gar_action_required', sa.String(length=255), nullable=True),
    sa.Column('is_gar_reviewed', sa.Boolean(), nullable=True),
    sa.Column('gar_chat_ready', sa.Boolean(), nullable=True),
    sa.Column('gar_feedback', sa.Text(), nullable=True),
    sa.Column('gar_last_message_at', sa.DateTime(), nullable=True),
    sa.Column('gar_resolution_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['country_config_id'], ['country_client_config.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leases')
    # ### end Alembic commands ###
