"""Add WorkOrderSettingsAuditLog Table

Revision ID: 365cc97f698a
Revises: a9c581cbdfbc
Create Date: 2025-07-15 20:38:28.394667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '365cc97f698a'
down_revision = 'a9c581cbdfbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_order_setting_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('setting_id', sa.Integer(), nullable=False),
    sa.Column('changed_by_id', sa.Integer(), nullable=False),
    sa.Column('change_type', sa.String(length=50), nullable=False),
    sa.Column('field_changed', sa.String(length=100), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('ai_impact_assessment', sa.Text(), nullable=True),
    sa.Column('gar_compliance_effect', sa.Text(), nullable=True),
    sa.Column('is_ai_flagged', sa.Boolean(), nullable=True),
    sa.Column('gar_score_delta', sa.Float(), nullable=True),
    sa.Column('parsed_summary', sa.Text(), nullable=True),
    sa.Column('extracted_data', sa.JSON(), nullable=True),
    sa.Column('parsing_status', sa.String(length=50), nullable=True),
    sa.Column('parsed_at', sa.DateTime(), nullable=True),
    sa.Column('parsed_by_ai_version', sa.String(length=50), nullable=True),
    sa.Column('gar_chat_ready', sa.Boolean(), nullable=True),
    sa.Column('gar_feedback', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['setting_id'], ['work_order_settings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_order_setting_audit_logs')
    # ### end Alembic commands ###
