"""Add DirectorAreaAssignment Table

Revision ID: 408ab5ef23d9
Revises: efd0b9d52fce
Create Date: 2025-07-15 20:59:09.917714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '408ab5ef23d9'
down_revision = 'efd0b9d52fce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('director_area_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('area', sa.String(length=100), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('director_area_assignments')
    # ### end Alembic commands ###
