"""Add Arrears table

Revision ID: 4285910e4af5
Revises: c8de13b1b5a0
Create Date: 2025-07-14 21:21:34.405036

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4285910e4af5'
down_revision = 'c8de13b1b5a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arrears',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('finance_batch_id', sa.Integer(), nullable=True),
    sa.Column('amount_due', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('days_overdue', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('late_fee_accrued', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('interest_accrued', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('interest_waived', sa.Boolean(), nullable=True),
    sa.Column('waiver_reason', sa.Text(), nullable=True),
    sa.Column('penalty_policy_applied', sa.String(length=100), nullable=True),
    sa.Column('parsed_summary', sa.Text(), nullable=True),
    sa.Column('extracted_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('flagged_by_ai', sa.Boolean(), nullable=True),
    sa.Column('reason_for_flag', sa.String(length=255), nullable=True),
    sa.Column('gar_compliance_score', sa.Float(), nullable=True),
    sa.Column('gar_risk_flag', sa.String(length=50), nullable=True),
    sa.Column('validated_by_gar', sa.Boolean(), nullable=True),
    sa.Column('gar_chat_ready', sa.Boolean(), nullable=True),
    sa.Column('gar_feedback', sa.Text(), nullable=True),
    sa.Column('source_document', sa.String(length=255), nullable=True),
    sa.Column('external_collection_ref', sa.String(length=100), nullable=True),
    sa.Column('arrears_type', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['finance_batch_id'], ['finance_batches.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('arrears')
    # ### end Alembic commands ###
