"""Add inspections table

Revision ID: 4aa279a1eace
Revises: 1b9378a70236
Create Date: 2025-07-12 16:52:02.185349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4aa279a1eace'
down_revision = '1b9378a70236'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inspections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=True),
    sa.Column('inspector_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('inspection_date', sa.Date(), nullable=False),
    sa.Column('next_due', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('inspected_remotely', sa.Boolean(), nullable=True),
    sa.Column('inspection_channel', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('document_filename', sa.String(length=255), nullable=True),
    sa.Column('attachments_count', sa.Integer(), nullable=True),
    sa.Column('media_uploaded', sa.Boolean(), nullable=True),
    sa.Column('doc_links', sa.JSON(), nullable=True),
    sa.Column('photo_links', sa.JSON(), nullable=True),
    sa.Column('ai_source_type', sa.String(length=50), nullable=True),
    sa.Column('visibility_scope', sa.String(length=100), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=True),
    sa.Column('consent_verified', sa.Boolean(), nullable=True),
    sa.Column('shared_with_director', sa.Boolean(), nullable=True),
    sa.Column('external_reference', sa.String(length=100), nullable=True),
    sa.Column('source_system', sa.String(length=100), nullable=True),
    sa.Column('is_external', sa.Boolean(), nullable=True),
    sa.Column('sync_status', sa.String(length=50), nullable=True),
    sa.Column('parsed_text', sa.Text(), nullable=True),
    sa.Column('ai_parsed_summary', sa.Text(), nullable=True),
    sa.Column('ai_flagged_issues', sa.Text(), nullable=True),
    sa.Column('ai_recommendations', sa.Text(), nullable=True),
    sa.Column('extracted_data', sa.JSON(), nullable=True),
    sa.Column('ai_confidence_score', sa.Float(), nullable=True),
    sa.Column('parsed_fields_confidence', sa.JSON(), nullable=True),
    sa.Column('ai_parsed_at', sa.DateTime(), nullable=True),
    sa.Column('parsed_by_ai_version', sa.String(length=50), nullable=True),
    sa.Column('parsing_status', sa.String(length=50), nullable=True),
    sa.Column('is_ai_processed', sa.Boolean(), nullable=True),
    sa.Column('ai_profile_locked', sa.Boolean(), nullable=True),
    sa.Column('ai_scorecard', sa.JSON(), nullable=True),
    sa.Column('ai_rank', sa.String(length=20), nullable=True),
    sa.Column('is_ai_preferred', sa.Boolean(), nullable=True),
    sa.Column('reason_for_recommendation', sa.Text(), nullable=True),
    sa.Column('flagged_sections', sa.JSON(), nullable=True),
    sa.Column('gar_chat_ready', sa.Boolean(), nullable=True),
    sa.Column('gar_feedback', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['inspector_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inspections')
    # ### end Alembic commands ###
