"""Add ManagementCompanyReview Table

Revision ID: 4bda135d6467
Revises: 236e34cffd6c
Create Date: 2025-07-17 20:52:02.595909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bda135d6467'
down_revision = '236e34cffd6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('management_company_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('director_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('review_period', sa.String(length=20), nullable=True),
    sa.Column('communication_rating', sa.Integer(), nullable=True),
    sa.Column('responsiveness_rating', sa.Integer(), nullable=True),
    sa.Column('financial_transparency_rating', sa.Integer(), nullable=True),
    sa.Column('value_rating', sa.Integer(), nullable=True),
    sa.Column('overall_satisfaction_rating', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('parsed_summary', sa.Text(), nullable=True),
    sa.Column('extracted_data', sa.JSON(), nullable=True),
    sa.Column('parsing_status', sa.String(length=50), nullable=True),
    sa.Column('parsed_at', sa.DateTime(), nullable=True),
    sa.Column('parsed_by_ai_version', sa.String(length=50), nullable=True),
    sa.Column('ai_source_type', sa.String(length=50), nullable=True),
    sa.Column('is_ai_processed', sa.Boolean(), nullable=True),
    sa.Column('gar_alignment_score', sa.Float(), nullable=True),
    sa.Column('gar_red_flags', sa.Text(), nullable=True),
    sa.Column('gar_confidence_rating', sa.Float(), nullable=True),
    sa.Column('is_gar_reviewed', sa.Boolean(), nullable=True),
    sa.Column('recommended_action', sa.String(length=200), nullable=True),
    sa.Column('gar_chat_ready', sa.Boolean(), nullable=True),
    sa.Column('gar_feedback', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['director_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employee_exit_processes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('termination_record_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'termination_records', ['termination_record_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_exit_processes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('termination_record_id')

    op.drop_table('management_company_reviews')
    # ### end Alembic commands ###
