"""add data_json to client_contracts and form_schema to contract_template_versions

Revision ID: 4c2f7f114bd0
Revises: 9e78186a0c12
Create Date: 2025-09-06 19:39:22.257701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c2f7f114bd0'
down_revision = '9e78186a0c12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contract_template_versions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('form_schema', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contract_template_versions', schema=None) as batch_op:
        batch_op.drop_column('form_schema')

    # ### end Alembic commands ###
