"""Add EmailLog model

Revision ID: 4c5cb3a7ef80
Revises: 3ab0f22d8c26
Create Date: 2025-07-27 15:03:02.865161

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4c5cb3a7ef80'
down_revision = '3ab0f22d8c26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('email_type', sa.String(length=100), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('delivery_status', sa.String(length=50), nullable=True),
    sa.Column('delivery_response', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('context_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('gar_summary', sa.Text(), nullable=True),
    sa.Column('ai_extracted_entities', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('is_gar_relevant', sa.Boolean(), nullable=True),
    sa.Column('audit_notes', sa.Text(), nullable=True),
    sa.Column('reviewed_by_admin', sa.Boolean(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('member_units',
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('ownership_percentage', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('member_id', 'unit_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('member_units')
    op.drop_table('email_logs')
    # ### end Alembic commands ###
