"""Enhance BudgetAllocationLog with AGM and draft status fields

Revision ID: 4c7ca7586d40
Revises: 77075dab00eb
Create Date: 2025-07-14 16:49:53.986517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c7ca7586d40'
down_revision = '77075dab00eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget_allocation_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved_by_user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_draft', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('agm_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('agm_reference', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('approved_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['approved_by_user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget_allocation_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('approved_at')
        batch_op.drop_column('agm_reference')
        batch_op.drop_column('agm_date')
        batch_op.drop_column('is_draft')
        batch_op.drop_column('approved_by_user_id')

    # ### end Alembic commands ###
