"""Add reconciliation engine table

Revision ID: 4e93569aa155
Revises: 949e8d3e6b4d
Create Date: 2025-07-13 13:13:07.670755

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4e93569aa155'
down_revision = '949e8d3e6b4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reconciliation_engine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reconciliation_batch_id', sa.Integer(), nullable=True),
    sa.Column('initiated_by_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('imported_statement_file', sa.String(length=255), nullable=True),
    sa.Column('imported_by_system', sa.String(length=100), nullable=True),
    sa.Column('system_snapshot_reference', sa.String(length=100), nullable=True),
    sa.Column('matching_method', sa.String(length=100), nullable=False),
    sa.Column('match_tolerance_days', sa.Integer(), nullable=True),
    sa.Column('amount_tolerance_cents', sa.Integer(), nullable=True),
    sa.Column('include_pending_transactions', sa.Boolean(), nullable=True),
    sa.Column('auto_confirm_high_confidence', sa.Boolean(), nullable=True),
    sa.Column('ai_confidence_threshold', sa.Float(), nullable=True),
    sa.Column('ai_flagged_items', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('parsed_summary', sa.Text(), nullable=True),
    sa.Column('parsed_data', sa.JSON(), nullable=True),
    sa.Column('gar_rules_applied', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('gar_risk_assessment', sa.Text(), nullable=True),
    sa.Column('gar_score', sa.String(length=20), nullable=True),
    sa.Column('requires_human_review', sa.Boolean(), nullable=True),
    sa.Column('approved_by_gar', sa.Boolean(), nullable=True),
    sa.Column('gar_chat_ready', sa.Boolean(), nullable=True),
    sa.Column('gar_feedback', sa.Text(), nullable=True),
    sa.Column('total_entries_matched', sa.Integer(), nullable=True),
    sa.Column('total_unmatched_entries', sa.Integer(), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('final_status', sa.String(length=50), nullable=True),
    sa.Column('reconciliation_status', sa.String(length=50), nullable=True),
    sa.Column('export_reference', sa.String(length=255), nullable=True),
    sa.Column('audit_log_reference', sa.String(length=255), nullable=True),
    sa.Column('reconciled_at', sa.DateTime(), nullable=True),
    sa.Column('reconciled_by_ai_version', sa.String(length=50), nullable=True),
    sa.Column('reconciliation_notes', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['initiated_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reconciliation_batch_id'], ['reconciliation_batches.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reconciliation_status', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('reconciliation_status')

    op.drop_table('reconciliation_engine')
    # ### end Alembic commands ###
