"""Add CAPEX profile fields, valuation details, AI/GAR fields to Client model

Revision ID: 4fa7923d7325
Revises: 240905c3898d
Create Date: 2025-08-11 20:27:55.640931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fa7923d7325'
down_revision = '240905c3898d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clients_assigned_pm_id'), ['assigned_pm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clients_company_id'), ['company_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clients_company_id'))
        batch_op.drop_index(batch_op.f('ix_clients_assigned_pm_id'))

    # ### end Alembic commands ###
