"""add server_default false to Contract booleans

Revision ID: 52c3a07899f5
Revises: b0957051253b
Create Date: 2025-09-23 13:15:05.266642

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '52c3a07899f5'
down_revision = 'b0957051253b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_contracts', schema=None) as batch_op:
        batch_op.alter_column('data_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.drop_constraint('fk_contract_parent', type_='foreignkey')
        batch_op.create_foreign_key(None, 'client_contracts', ['parent_contract_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_contracts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_contract_parent', 'client_contracts', ['parent_contract_id'], ['id'], ondelete='SET NULL')
        batch_op.alter_column('data_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)

    # ### end Alembic commands ###
