"""Add CapexRequest Table

Revision ID: 5a9dd96e8c7e
Revises: ec71dc3e0cf0
Create Date: 2025-07-15 15:30:15.692750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a9dd96e8c7e'
down_revision = 'ec71dc3e0cf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capex_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('urgency', sa.String(length=50), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('file', sa.String(length=200), nullable=True),
    sa.Column('submitted_by', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('is_owner', sa.Boolean(), nullable=True),
    sa.Column('is_resident', sa.Boolean(), nullable=True),
    sa.Column('consent_to_publish', sa.Boolean(), nullable=True),
    sa.Column('visibility_roles', sa.String(length=255), nullable=True),
    sa.Column('gdpr_flagged', sa.Boolean(), nullable=True),
    sa.Column('parsed_summary', sa.Text(), nullable=True),
    sa.Column('extracted_data', sa.JSON(), nullable=True),
    sa.Column('parsing_status', sa.String(length=50), nullable=True),
    sa.Column('parsed_at', sa.DateTime(), nullable=True),
    sa.Column('parsed_by_ai_version', sa.String(length=50), nullable=True),
    sa.Column('ai_source_type', sa.String(length=50), nullable=True),
    sa.Column('is_ai_processed', sa.Boolean(), nullable=True),
    sa.Column('gar_flagged_risks', sa.Text(), nullable=True),
    sa.Column('gar_recommendations', sa.Text(), nullable=True),
    sa.Column('gar_alignment_score', sa.Float(), nullable=True),
    sa.Column('gar_suggested_priority', sa.String(length=20), nullable=True),
    sa.Column('gar_recommendation_reason', sa.Text(), nullable=True),
    sa.Column('gar_review_score', sa.Float(), nullable=True),
    sa.Column('is_gar_flagged', sa.Boolean(), nullable=True),
    sa.Column('gar_chat_ready', sa.Boolean(), nullable=True),
    sa.Column('gar_feedback', sa.Text(), nullable=True),
    sa.Column('tags', sa.String(length=255), nullable=True),
    sa.Column('capex_type', sa.String(length=100), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('capex_requests')
    # ### end Alembic commands ###
