"""Add country_client_config table

Revision ID: 5bc37627f423
Revises: d723f18f0807
Create Date: 2025-07-13 13:39:50.395739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bc37627f423'
down_revision = 'd723f18f0807'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country_client_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('client_type', sa.String(length=100), nullable=False),
    sa.Column('legal_basis', sa.String(length=500), nullable=True),
    sa.Column('governing_body', sa.String(length=150), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('ownership_types', sa.Text(), nullable=True),
    sa.Column('timezones', sa.Text(), nullable=True),
    sa.Column('regions', sa.Text(), nullable=True),
    sa.Column('is_commercial', sa.Boolean(), nullable=True),
    sa.Column('deed_required', sa.Boolean(), nullable=True),
    sa.Column('min_directors', sa.Integer(), nullable=True),
    sa.Column('max_directors', sa.Integer(), nullable=True),
    sa.Column('resident_equivalence_logic', sa.String(length=100), nullable=True),
    sa.Column('data_protection_compliance', sa.Boolean(), nullable=True),
    sa.Column('requires_gdpr_consent', sa.Boolean(), nullable=True),
    sa.Column('default_visibility_scope', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('document_filename', sa.String(length=255), nullable=True),
    sa.Column('ai_parsed_legal_summary', sa.Text(), nullable=True),
    sa.Column('ai_key_clauses', sa.JSON(), nullable=True),
    sa.Column('ai_risks_or_exceptions', sa.Text(), nullable=True),
    sa.Column('ai_ownership_recommendations', sa.Text(), nullable=True),
    sa.Column('ai_timezone_map', sa.Text(), nullable=True),
    sa.Column('ai_region_map', sa.Text(), nullable=True),
    sa.Column('ai_source_type', sa.String(length=50), nullable=True),
    sa.Column('ai_confidence_score', sa.Float(), nullable=True),
    sa.Column('ai_parsed_at', sa.DateTime(), nullable=True),
    sa.Column('parsed_by_ai_version', sa.String(length=50), nullable=True),
    sa.Column('is_ai_processed', sa.Boolean(), nullable=True),
    sa.Column('gar_legal_alignment_rating', sa.String(length=20), nullable=True),
    sa.Column('gar_recommended_tag', sa.String(length=100), nullable=True),
    sa.Column('gar_summary_recommendation', sa.Text(), nullable=True),
    sa.Column('gar_flagged_policy_gaps', sa.Text(), nullable=True),
    sa.Column('gar_chat_ready', sa.Boolean(), nullable=True),
    sa.Column('gar_feedback', sa.Text(), nullable=True),
    sa.Column('gar_last_message_at', sa.DateTime(), nullable=True),
    sa.Column('gar_resolution_status', sa.String(length=50), nullable=True),
    sa.Column('last_verified_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['last_verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bank_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('levy_payment_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'levy_payments', ['levy_payment_id'], ['id'])

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'companies', ['company_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'clients', ['company_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('company_id')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('company_id')

    with op.batch_alter_table('bank_transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('levy_payment_id')

    op.drop_table('country_client_config')
    # ### end Alembic commands ###
