"""create clients table

Revision ID: 5c10eed65262
Revises: ee1631b4fab4
Create Date: 2025-07-11 13:31:18.380610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c10eed65262'
down_revision = 'ee1631b4fab4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=250), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('registration_number', sa.String(length=50), nullable=True),
    sa.Column('vat_reg_number', sa.String(length=50), nullable=True),
    sa.Column('tax_number', sa.String(length=50), nullable=True),
    sa.Column('year_of_construction', sa.String(length=10), nullable=True),
    sa.Column('number_of_units', sa.Integer(), nullable=True),
    sa.Column('client_type', sa.String(length=50), nullable=True),
    sa.Column('contract_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('financial_year_end', sa.Date(), nullable=True),
    sa.Column('last_agm_date', sa.Date(), nullable=True),
    sa.Column('agm_completed', sa.Boolean(), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('preferred_language', sa.String(length=50), nullable=True),
    sa.Column('ownership_type', sa.String(length=50), nullable=True),
    sa.Column('transfer_of_common_area', sa.Boolean(), nullable=True),
    sa.Column('deed_of_covenants', sa.String(length=250), nullable=True),
    sa.Column('data_protection_compliance', sa.String(length=50), nullable=True),
    sa.Column('consent_to_communicate', sa.Boolean(), nullable=True),
    sa.Column('resident_logic', sa.String(length=100), nullable=True),
    sa.Column('enforce_gdpr', sa.Boolean(), nullable=True),
    sa.Column('default_visibility_scope', sa.String(length=100), nullable=True),
    sa.Column('min_directors', sa.Integer(), nullable=True),
    sa.Column('max_directors', sa.Integer(), nullable=True),
    sa.Column('number_of_blocks', sa.Integer(), nullable=True),
    sa.Column('block_names', sa.String(length=300), nullable=True),
    sa.Column('cores_per_block', sa.String(length=300), nullable=True),
    sa.Column('apartments_per_block', sa.String(length=300), nullable=True),
    sa.Column('assigned_pm_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('reinstatement_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('reinstatement_valuation_date', sa.Date(), nullable=True),
    sa.Column('ai_valuation_analysis', sa.Text(), nullable=True),
    sa.Column('ai_insurance_trend_flag', sa.Text(), nullable=True),
    sa.Column('document_filename', sa.String(length=255), nullable=True),
    sa.Column('ai_parsed_contract_terms', sa.Text(), nullable=True),
    sa.Column('ai_governance_summary', sa.Text(), nullable=True),
    sa.Column('ai_ownership_structure_analysis', sa.Text(), nullable=True),
    sa.Column('ai_service_charge_insight', sa.Text(), nullable=True),
    sa.Column('ai_flagged_risks', sa.Text(), nullable=True),
    sa.Column('parsed_at', sa.DateTime(), nullable=True),
    sa.Column('parsed_by_ai_version', sa.String(length=50), nullable=True),
    sa.Column('ai_source_type', sa.String(length=50), nullable=True),
    sa.Column('is_ai_processed', sa.Boolean(), nullable=True),
    sa.Column('ai_governance_score', sa.Float(), nullable=True),
    sa.Column('ai_compliance_index', sa.Float(), nullable=True),
    sa.Column('ai_health_index', sa.Float(), nullable=True),
    sa.Column('ai_trend_insight', sa.Text(), nullable=True),
    sa.Column('ai_advice_summary', sa.Text(), nullable=True),
    sa.Column('ai_prediction_flags', sa.String(length=300), nullable=True),
    sa.Column('ai_risk_level', sa.String(length=50), nullable=True),
    sa.Column('is_gar_monitored', sa.Boolean(), nullable=True),
    sa.Column('gar_chat_ready', sa.Boolean(), nullable=True),
    sa.Column('gar_feedback', sa.Text(), nullable=True),
    sa.Column('gar_last_message_at', sa.DateTime(), nullable=True),
    sa.Column('gar_resolution_status', sa.String(length=50), nullable=True),
    sa.Column('ownership_types', sa.JSON(), nullable=True),
    sa.Column('ai_key_clauses', sa.JSON(), nullable=True),
    sa.Column('tags', sa.String(length=255), nullable=True),
    sa.Column('capex_profile', sa.String(length=100), nullable=True),
    sa.Column('ai_last_reviewed_by', sa.Integer(), nullable=True),
    sa.Column('ai_review_comment', sa.Text(), nullable=True),
    sa.Column('ai_last_reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ai_last_reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['assigned_pm_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clients')
    # ### end Alembic commands ###
