"""create companies table

Revision ID: 62a55b88ee9b
Revises: 
Create Date: 2025-07-11 13:04:49.954759

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '62a55b88ee9b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('vat_number', sa.String(length=100), nullable=True),
    sa.Column('tax_identifier', sa.String(length=100), nullable=True),
    sa.Column('company_type', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('timezone', sa.String(length=100), nullable=True),
    sa.Column('preferred_language', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=50), nullable=True),
    sa.Column('data_protection_compliant', sa.Boolean(), nullable=True),
    sa.Column('terms_agreed', sa.Boolean(), nullable=True),
    sa.Column('consent_to_communicate', sa.Boolean(), nullable=True),
    sa.Column('default_settings', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('logo_path', sa.String(length=255), nullable=True),
    sa.Column('brand_color', sa.String(length=20), nullable=True),
    sa.Column('ai_behavior_profile', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('gar_access_enabled', sa.Boolean(), nullable=True),
    sa.Column('gar_training_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('gar_internal_score', sa.String(length=20), nullable=True),
    sa.Column('ai_notes', sa.Text(), nullable=True),
    sa.Column('gar_chat_ready', sa.Boolean(), nullable=True),
    sa.Column('gar_feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('integrations', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('sync_status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('companies')
    # ### end Alembic commands ###
