"""Add JournalBatch table

Revision ID: 64bfee80676a
Revises: a6eae284ac1a
Create Date: 2025-07-13 14:20:31.212001

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '64bfee80676a'
down_revision = 'a6eae284ac1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('period', sa.String(length=20), nullable=True),
    sa.Column('journal_date', sa.Date(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('parsed_text', sa.Text(), nullable=True),
    sa.Column('parsed_summary', sa.Text(), nullable=True),
    sa.Column('extracted_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_scorecard', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('gar_notes', sa.Text(), nullable=True),
    sa.Column('gar_context_reference', sa.String(length=100), nullable=True),
    sa.Column('flagged_by_gar', sa.Boolean(), nullable=True),
    sa.Column('context_tags', sa.ARRAY(sa.String(length=50)), nullable=True),
    sa.Column('role_visibility', sa.ARRAY(sa.String(length=50)), nullable=True),
    sa.Column('external_reference', sa.String(length=100), nullable=True),
    sa.Column('external_system', sa.String(length=100), nullable=True),
    sa.Column('sync_status', sa.String(length=50), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journal_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_batches_batch_name'), ['batch_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_batches_journal_date'), ['journal_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_batches_period'), ['period'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_batches_period'))
        batch_op.drop_index(batch_op.f('ix_journal_batches_journal_date'))
        batch_op.drop_index(batch_op.f('ix_journal_batches_batch_name'))

    op.drop_table('journal_batches')
    # ### end Alembic commands ###
