"""Add CapexResponse Table

Revision ID: 68186dd41422
Revises: 5a9dd96e8c7e
Create Date: 2025-07-15 15:32:27.392841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68186dd41422'
down_revision = '5a9dd96e8c7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capex_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capex_request_id', sa.Integer(), nullable=False),
    sa.Column('submitted_by', sa.Integer(), nullable=False),
    sa.Column('contractor_name', sa.String(length=100), nullable=False),
    sa.Column('quote_amount', sa.Float(), nullable=False),
    sa.Column('file', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('parsed_summary', sa.Text(), nullable=True),
    sa.Column('extracted_data', sa.JSON(), nullable=True),
    sa.Column('parsing_status', sa.String(length=50), nullable=True),
    sa.Column('parsed_at', sa.DateTime(), nullable=True),
    sa.Column('parsed_by_ai_version', sa.String(length=50), nullable=True),
    sa.Column('ai_source_type', sa.String(length=50), nullable=True),
    sa.Column('is_ai_processed', sa.Boolean(), nullable=True),
    sa.Column('ai_scorecard', sa.JSON(), nullable=True),
    sa.Column('ai_rank', sa.Integer(), nullable=True),
    sa.Column('is_ai_preferred', sa.Boolean(), nullable=True),
    sa.Column('reason_for_recommendation', sa.Text(), nullable=True),
    sa.Column('gar_chat_ready', sa.Boolean(), nullable=True),
    sa.Column('gar_feedback', sa.Text(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('visibility_roles', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['capex_request_id'], ['capex_requests.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('capex_responses')
    # ### end Alembic commands ###
