"""Link LedgerEntry to LedgerBatch

Revision ID: 6af12c1a0afd
Revises: ad423178f9b3
Create Date: 2025-07-21 09:21:32.956527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6af12c1a0afd'
down_revision = 'ad423178f9b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ledger_batch_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'ledger_batches', ['ledger_batch_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('ledger_batch_id')

    # ### end Alembic commands ###
