"""Add EmployeeOnboarding Table

Revision ID: 6d662adeb681
Revises: 33d73f8d254c
Create Date: 2025-07-17 20:41:33.109892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d662adeb681'
down_revision = '33d73f8d254c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_onboarding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('onboarding_status', sa.String(length=50), nullable=True),
    sa.Column('onboarding_type', sa.String(length=50), nullable=True),
    sa.Column('current_step', sa.String(length=100), nullable=True),
    sa.Column('step_notes', sa.Text(), nullable=True),
    sa.Column('contract_signed', sa.Boolean(), nullable=True),
    sa.Column('documents_uploaded', sa.Boolean(), nullable=True),
    sa.Column('hr_policy_acknowledged', sa.Boolean(), nullable=True),
    sa.Column('induction_completed', sa.Boolean(), nullable=True),
    sa.Column('equipment_issued', sa.Boolean(), nullable=True),
    sa.Column('job_title', sa.String(length=100), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('completion_date', sa.DateTime(), nullable=True),
    sa.Column('ai_onboarding_path', sa.JSON(), nullable=True),
    sa.Column('gar_summary', sa.Text(), nullable=True),
    sa.Column('gar_flagged_gaps', sa.Text(), nullable=True),
    sa.Column('gar_readiness_score', sa.Float(), nullable=True),
    sa.Column('ai_confidence_score', sa.Float(), nullable=True),
    sa.Column('parsed_by_ai_version', sa.String(length=50), nullable=True),
    sa.Column('is_ai_processed', sa.Boolean(), nullable=True),
    sa.Column('gar_chat_ready', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee_onboarding')
    # ### end Alembic commands ###
