"""Add BudgetAllocationLog table

Revision ID: 77075dab00eb
Revises: 2c69f8e261da
Create Date: 2025-07-14 09:08:54.740051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77075dab00eb'
down_revision = '2c69f8e261da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget_allocation_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('calculated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('total_budget_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('allocated_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('allocation_method', sa.String(length=50), nullable=False),
    sa.Column('apportionment_value', sa.Float(), nullable=True),
    sa.Column('ai_flagged', sa.Boolean(), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('gar_flag', sa.Boolean(), nullable=True),
    sa.Column('gar_reason', sa.Text(), nullable=True),
    sa.Column('gar_risk_score', sa.Float(), nullable=True),
    sa.Column('parsed_summary', sa.Text(), nullable=True),
    sa.Column('ai_comments', sa.Text(), nullable=True),
    sa.Column('allocation_period', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['calculated_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('budget_allocation_logs')
    # ### end Alembic commands ###
