"""Add GeneratedReportLog table

Revision ID: 7b802308599a
Revises: 4c7ca7586d40
Create Date: 2025-07-14 16:53:34.883600

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7b802308599a'
down_revision = '4c7ca7586d40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_report_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('generated_by_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('report_name', sa.String(length=255), nullable=True),
    sa.Column('output_format', sa.String(length=10), nullable=True),
    sa.Column('output_path', sa.String(length=255), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('report_status', sa.String(length=50), nullable=True),
    sa.Column('parsed_summary', sa.Text(), nullable=True),
    sa.Column('parsed_text', sa.Text(), nullable=True),
    sa.Column('extracted_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_scorecard', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_analysis', sa.Text(), nullable=True),
    sa.Column('gar_insight_score', sa.Float(), nullable=True),
    sa.Column('gar_recommendations', sa.Text(), nullable=True),
    sa.Column('gar_context_reference', sa.String(length=100), nullable=True),
    sa.Column('flagged_by_gar', sa.Boolean(), nullable=True),
    sa.Column('context_tags', sa.ARRAY(sa.String(length=50)), nullable=True),
    sa.Column('role_visibility', sa.ARRAY(sa.String(length=50)), nullable=True),
    sa.Column('gar_chat_ready', sa.Boolean(), nullable=True),
    sa.Column('gar_feedback', sa.Text(), nullable=True),
    sa.Column('external_export_id', sa.String(length=100), nullable=True),
    sa.Column('synced_with', sa.String(length=50), nullable=True),
    sa.Column('sync_status', sa.String(length=50), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('ip_generated_from', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['generated_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('generated_report_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generated_report_logs_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_generated_report_logs_generated_at'), ['generated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_generated_report_logs_generated_by_id'), ['generated_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_generated_report_logs_report_name'), ['report_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generated_report_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generated_report_logs_report_name'))
        batch_op.drop_index(batch_op.f('ix_generated_report_logs_generated_by_id'))
        batch_op.drop_index(batch_op.f('ix_generated_report_logs_generated_at'))
        batch_op.drop_index(batch_op.f('ix_generated_report_logs_client_id'))

    op.drop_table('generated_report_logs')
    # ### end Alembic commands ###
