"""Add AnnualServiceChargeStatements table

Revision ID: 7c9d2eb13989
Revises: 79fb708c25a3
Create Date: 2025-07-14 21:10:17.513064

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7c9d2eb13989'
down_revision = '79fb708c25a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annual_service_charge_statements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('period_label', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('total_charged', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_paid', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_outstanding', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('late_fees_applied', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('interest_applied', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('statement_url', sa.String(length=255), nullable=True),
    sa.Column('supporting_documents', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parsed_summary', sa.Text(), nullable=True),
    sa.Column('extracted_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('gar_score', sa.Float(), nullable=True),
    sa.Column('gar_flagged', sa.Boolean(), nullable=True),
    sa.Column('gar_flag_reason', sa.String(length=255), nullable=True),
    sa.Column('ai_notes', sa.Text(), nullable=True),
    sa.Column('gar_context_reference', sa.String(length=100), nullable=True),
    sa.Column('is_gar_verified', sa.Boolean(), nullable=True),
    sa.Column('is_finalised', sa.Boolean(), nullable=True),
    sa.Column('validated_by_id', sa.Integer(), nullable=True),
    sa.Column('validated_at', sa.DateTime(), nullable=True),
    sa.Column('integration_status', sa.String(length=50), nullable=True),
    sa.Column('external_reference', sa.String(length=150), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.ForeignKeyConstraint(['validated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('annual_service_charge_statements')
    # ### end Alembic commands ###
