"""Client: add property_name and transfer_of_common_area_date

Revision ID: 818ce89f3c18
Revises: b9f87d649c8d
Create Date: 2025-09-04 07:34:10.447474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '818ce89f3c18'
down_revision = 'b9f87d649c8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('property_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('transfer_of_common_area_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('transfer_of_common_area_date')
        batch_op.drop_column('property_name')

    # ### end Alembic commands ###
