"""Fix user relationship to Company and Contractor

Revision ID: 87f5e76060dc
Revises: 55714608ab80
Create Date: 2025-07-21 11:55:16.076526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87f5e76060dc'
down_revision = '55714608ab80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_client', type_='foreignkey')
        batch_op.create_foreign_key('fk_user_company', 'companies', ['company_id'], ['id'], initially='DEFERRED', deferrable=True, use_alter=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_company', type_='foreignkey')
        batch_op.create_foreign_key('fk_user_client', 'clients', ['company_id'], ['id'], initially='DEFERRED', deferrable=True)

    # ### end Alembic commands ###
