"""Add AGM table

Revision ID: 89e534a13561
Revises: 34da33174acd
Create Date: 2025-07-14 22:30:42.790115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89e534a13561'
down_revision = '34da33174acd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('block_name', sa.String(length=100), nullable=True),
    sa.Column('meeting_title', sa.String(length=255), nullable=False),
    sa.Column('meeting_date', sa.Date(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('called_by_id', sa.Integer(), nullable=True),
    sa.Column('agenda_file', sa.String(length=500), nullable=True),
    sa.Column('minutes_file', sa.String(length=500), nullable=True),
    sa.Column('resolutions_file', sa.String(length=500), nullable=True),
    sa.Column('parsed_text', sa.Text(), nullable=True),
    sa.Column('parsed_summary', sa.Text(), nullable=True),
    sa.Column('extracted_data', sa.Text(), nullable=True),
    sa.Column('ai_confidence_score', sa.Float(), nullable=True),
    sa.Column('reviewed_by_ai', sa.Boolean(), nullable=True),
    sa.Column('ai_parsed_at', sa.DateTime(), nullable=True),
    sa.Column('ai_source_type', sa.String(length=50), nullable=True),
    sa.Column('gar_chat_ready', sa.Boolean(), nullable=True),
    sa.Column('gar_feedback', sa.Text(), nullable=True),
    sa.Column('gar_last_message_at', sa.DateTime(), nullable=True),
    sa.Column('gar_resolution_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by_human', sa.Boolean(), nullable=True),
    sa.Column('last_reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('visibility_roles', sa.String(length=255), nullable=True),
    sa.Column('tags', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['called_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lease_apportionment_schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lease_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'leases', ['lease_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lease_apportionment_schedules', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('lease_id')

    op.drop_table('agms')
    # ### end Alembic commands ###
