"""Add BoardMeetingAttendee table

Revision ID: 9086c840c85a
Revises: 0483711abf0b
Create Date: 2025-07-15 09:41:02.264884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9086c840c85a'
down_revision = '0483711abf0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board_meeting_attendees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('board_meeting_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('join_time', sa.DateTime(), nullable=True),
    sa.Column('leave_time', sa.DateTime(), nullable=True),
    sa.Column('is_virtual', sa.Boolean(), nullable=True),
    sa.Column('role_in_meeting', sa.String(length=100), nullable=True),
    sa.Column('attendance_status', sa.String(length=50), nullable=True),
    sa.Column('voted', sa.Boolean(), nullable=True),
    sa.Column('voting_method', sa.String(length=50), nullable=True),
    sa.Column('vote_record', sa.Text(), nullable=True),
    sa.Column('engagement_score', sa.Float(), nullable=True),
    sa.Column('gar_flagged_participation', sa.Text(), nullable=True),
    sa.Column('reviewed_by_gar', sa.Boolean(), nullable=True),
    sa.Column('gar_notes', sa.Text(), nullable=True),
    sa.Column('meeting_feedback', sa.Text(), nullable=True),
    sa.Column('ai_presence_tracking_data', sa.JSON(), nullable=True),
    sa.Column('attendance_file', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['board_meeting_id'], ['board_meetings.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('board_meeting_attendees')
    # ### end Alembic commands ###
