"""Add LedgerBatch Table

Revision ID: 934d2c5a6d28
Revises: 2eb4371bcb71
Create Date: 2025-07-13 14:34:59.554536

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '934d2c5a6d28'
down_revision = '2eb4371bcb71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ledger_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('batch_date', sa.DateTime(), nullable=True),
    sa.Column('total_entries', sa.Integer(), nullable=True),
    sa.Column('total_debit', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total_credit', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('is_balanced', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('posted_by_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('gar_context_reference', sa.String(length=100), nullable=True),
    sa.Column('gar_notes', sa.Text(), nullable=True),
    sa.Column('parsed_summary', sa.Text(), nullable=True),
    sa.Column('parsed_text', sa.Text(), nullable=True),
    sa.Column('extracted_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_scorecard', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('flagged_by_gar', sa.Boolean(), nullable=True),
    sa.Column('context_tags', sa.ARRAY(sa.String(length=50)), nullable=True),
    sa.Column('role_visibility', sa.ARRAY(sa.String(length=50)), nullable=True),
    sa.Column('third_party_batch_id', sa.String(length=100), nullable=True),
    sa.Column('external_system', sa.String(length=100), nullable=True),
    sa.Column('sync_status', sa.String(length=50), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['posted_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ledger_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ledger_batches_batch_date'), ['batch_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_batches_batch_name'), ['batch_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_batches_currency'), ['currency'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_batches_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ledger_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ledger_batches_status'))
        batch_op.drop_index(batch_op.f('ix_ledger_batches_currency'))
        batch_op.drop_index(batch_op.f('ix_ledger_batches_batch_name'))
        batch_op.drop_index(batch_op.f('ix_ledger_batches_batch_date'))

    op.drop_table('ledger_batches')
    # ### end Alembic commands ###
