"""Add QuoteResponse Table

Revision ID: 947d845a5091
Revises: 51f40648f1be
Create Date: 2025-07-15 20:44:35.491440

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '947d845a5091'
down_revision = '51f40648f1be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quote_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_order_id', sa.Integer(), nullable=False),
    sa.Column('contractor_id', sa.Integer(), nullable=False),
    sa.Column('submitted_by_id', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('quote_deadline', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('is_selected', sa.Boolean(), nullable=True),
    sa.Column('quote_file_path', sa.String(length=255), nullable=False),
    sa.Column('additional_files', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parsed_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('parsed_summary', sa.Text(), nullable=True),
    sa.Column('parsed_items', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('parsing_status', sa.String(length=50), nullable=True),
    sa.Column('parsed_by_ai_version', sa.String(length=50), nullable=True),
    sa.Column('parsed_at', sa.DateTime(), nullable=True),
    sa.Column('ai_scorecard', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_rank', sa.Integer(), nullable=True),
    sa.Column('is_ai_preferred', sa.Boolean(), nullable=True),
    sa.Column('reason_for_recommendation', sa.Text(), nullable=True),
    sa.Column('gar_flagged', sa.Boolean(), nullable=True),
    sa.Column('gar_alignment_score', sa.Float(), nullable=True),
    sa.Column('gar_recommendation', sa.Text(), nullable=True),
    sa.Column('gar_chat_enabled', sa.Boolean(), nullable=True),
    sa.Column('gar_chat_notes', sa.Text(), nullable=True),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('template_used', sa.String(length=100), nullable=True),
    sa.Column('template_generated', sa.Boolean(), nullable=True),
    sa.Column('template_generated_at', sa.DateTime(), nullable=True),
    sa.Column('visible_to_admin', sa.Boolean(), nullable=True),
    sa.Column('visible_to_creator', sa.Boolean(), nullable=True),
    sa.Column('visibility_scope', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['contractor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quote_responses')
    # ### end Alembic commands ###
