"""Add ExportedFileLog Table

Revision ID: 955b554874bb
Revises: 408ab5ef23d9
Create Date: 2025-07-15 21:01:13.837661

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '955b554874bb'
down_revision = '408ab5ef23d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exported_file_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('export_type', sa.String(length=100), nullable=False),
    sa.Column('related_model', sa.String(length=100), nullable=True),
    sa.Column('related_id', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('file_format', sa.String(length=10), nullable=False),
    sa.Column('file_name', sa.String(length=150), nullable=True),
    sa.Column('download_url', sa.String(length=255), nullable=True),
    sa.Column('visibility_scope', sa.String(length=50), nullable=True),
    sa.Column('is_sensitive', sa.Boolean(), nullable=True),
    sa.Column('redacted_for_public', sa.Boolean(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('resident_id', sa.Integer(), nullable=True),
    sa.Column('parsed_summary', sa.Text(), nullable=True),
    sa.Column('extracted_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('gar_context_reference', sa.String(length=100), nullable=True),
    sa.Column('gar_notes', sa.Text(), nullable=True),
    sa.Column('flagged_by_gar', sa.Boolean(), nullable=True),
    sa.Column('exported_by_id', sa.Integer(), nullable=True),
    sa.Column('exported_at', sa.DateTime(), nullable=True),
    sa.Column('is_api_exposed', sa.Boolean(), nullable=True),
    sa.Column('metadata_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['exported_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resident_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exported_file_logs')
    # ### end Alembic commands ###
