"""Add CAPEX project tables

Revision ID: 9593a2e00d3c
Revises: 4fa7923d7325
Create Date: 2025-08-12 16:12:45.448835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9593a2e00d3c'
down_revision = '4fa7923d7325'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capex_projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('target_year', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('priority', sa.String(length=10), server_default='Medium', nullable=False),
    sa.Column('funding', sa.String(length=20), server_default='Reserve Fund', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='Planned', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('capex_projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_capex_projects_client_id'), ['client_id'], unique=False)

    op.create_table('capex_project_dependencies',
    sa.Column('parent_id', sa.UUID(), nullable=False),
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['capex_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['capex_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('parent_id', 'child_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('capex_project_dependencies')
    with op.batch_alter_table('capex_projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_capex_projects_client_id'))

    op.drop_table('capex_projects')
    # ### end Alembic commands ###
