"""Add AGM tracking to Client model

Revision ID: 9933d997a639
Revises: dcebf41283b1
Create Date: 2025-06-25 08:37:57.087661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9933d997a639'
down_revision = 'dcebf41283b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('financial_year_end', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('last_agm_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('last_agm_date')
        batch_op.drop_column('financial_year_end')

    # ### end Alembic commands ###
