"""Fix circular dependencies in MaintenanceRequest model

Revision ID: a09a0b7dfdd9
Revises: 86f898093553
Create Date: 2025-07-15 21:37:01.772184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a09a0b7dfdd9'
down_revision = '86f898093553'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_requests', schema=None) as batch_op:
        batch_op.drop_constraint('maintenance_requests_requested_by_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('maintenance_requests_member_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('maintenance_requests_unit_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('maintenance_requests_work_order_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key('fk_mr_requested_by', 'users', ['requested_by_id'], ['id'], initially='DEFERRED', deferrable=True, use_alter=True)
        batch_op.create_foreign_key('fk_mr_member', 'members', ['member_id'], ['id'], initially='DEFERRED', deferrable=True, use_alter=True)
        batch_op.create_foreign_key('fk_mr_unit', 'units', ['unit_id'], ['id'], initially='DEFERRED', deferrable=True, use_alter=True)
        batch_op.create_foreign_key('fk_mr_work_order', 'work_orders', ['work_order_id'], ['id'], initially='DEFERRED', deferrable=True, use_alter=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_requests', schema=None) as batch_op:
        batch_op.drop_constraint('fk_mr_work_order', type_='foreignkey')
        batch_op.drop_constraint('fk_mr_unit', type_='foreignkey')
        batch_op.drop_constraint('fk_mr_member', type_='foreignkey')
        batch_op.drop_constraint('fk_mr_requested_by', type_='foreignkey')
        batch_op.create_foreign_key('maintenance_requests_work_order_id_fkey', 'work_orders', ['work_order_id'], ['id'])
        batch_op.create_foreign_key('maintenance_requests_unit_id_fkey', 'units', ['unit_id'], ['id'])
        batch_op.create_foreign_key('maintenance_requests_member_id_fkey', 'members', ['member_id'], ['id'])
        batch_op.create_foreign_key('maintenance_requests_requested_by_id_fkey', 'users', ['requested_by_id'], ['id'])

    # ### end Alembic commands ###
