"""create contract_audits

Revision ID: a1970031460f
Revises: 0c078bd4992c
Create Date: 2025-09-11 17:21:48.817928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1970031460f'
down_revision = '0c078bd4992c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('detail_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['client_contracts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contract_audits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contract_audits_contract_id'), ['contract_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contract_audits_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contract_audits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contract_audits_user_id'))
        batch_op.drop_index(batch_op.f('ix_contract_audits_contract_id'))

    op.drop_table('contract_audits')
    # ### end Alembic commands ###
