"""Add UserPolicyAcknowledgement Table

Revision ID: a1f791bf7ac3
Revises: 7c5f176bf234
Create Date: 2025-07-17 21:23:21.003033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1f791bf7ac3'
down_revision = '7c5f176bf234'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_policy_acknowledgements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('hr_profile_id', sa.Integer(), nullable=True),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged_by_user', sa.Boolean(), nullable=True),
    sa.Column('signature_captured', sa.Boolean(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('device_info', sa.String(length=255), nullable=True),
    sa.Column('version_acknowledged', sa.String(length=20), nullable=True),
    sa.Column('policy_snapshot', sa.Text(), nullable=True),
    sa.Column('parsed_summary', sa.Text(), nullable=True),
    sa.Column('extracted_data', sa.JSON(), nullable=True),
    sa.Column('parsing_status', sa.String(length=50), nullable=True),
    sa.Column('parsed_at', sa.DateTime(), nullable=True),
    sa.Column('parsed_by_ai_version', sa.String(length=50), nullable=True),
    sa.Column('ai_source_type', sa.String(length=50), nullable=True),
    sa.Column('is_ai_processed', sa.Boolean(), nullable=True),
    sa.Column('gar_flags', sa.Text(), nullable=True),
    sa.Column('gar_trust_score', sa.Float(), nullable=True),
    sa.Column('gar_compliance_notes', sa.Text(), nullable=True),
    sa.Column('is_gar_verified', sa.Boolean(), nullable=True),
    sa.Column('gar_chat_ready', sa.Boolean(), nullable=True),
    sa.Column('gar_feedback', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['employment_contracts.id'], ),
    sa.ForeignKeyConstraint(['hr_profile_id'], ['hr_profiles.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['hr_policies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_policy_acknowledgements')
    # ### end Alembic commands ###
