"""Add CrossBorderTaxCompliance table

Revision ID: a378e9e8b9a6
Revises: 3972d67b5351
Create Date: 2025-07-14 18:53:02.491101

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a378e9e8b9a6'
down_revision = '3972d67b5351'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cross_border_tax_compliance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=100), nullable=False),
    sa.Column('origin_country', sa.String(length=100), nullable=False),
    sa.Column('destination_country', sa.String(length=100), nullable=False),
    sa.Column('tax_rate_applied', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tax_code', sa.String(length=50), nullable=True),
    sa.Column('is_reverse_charge', sa.Boolean(), nullable=True),
    sa.Column('is_tax_exempt', sa.Boolean(), nullable=True),
    sa.Column('exemption_reason', sa.String(length=255), nullable=True),
    sa.Column('compliance_notes', sa.Text(), nullable=True),
    sa.Column('related_invoice_id', sa.Integer(), nullable=True),
    sa.Column('related_transaction_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('flagged_by_gar', sa.Boolean(), nullable=True),
    sa.Column('gar_risk_level', sa.String(length=50), nullable=True),
    sa.Column('gar_notes', sa.Text(), nullable=True),
    sa.Column('parsed_summary', sa.Text(), nullable=True),
    sa.Column('extracted_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('gar_context_reference', sa.String(length=100), nullable=True),
    sa.Column('gar_chat_ready', sa.Boolean(), nullable=True),
    sa.Column('gar_feedback', sa.Text(), nullable=True),
    sa.Column('external_tax_service_id', sa.String(length=100), nullable=True),
    sa.Column('integration_status', sa.String(length=50), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['modified_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['related_invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['related_transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cross_border_tax_compliance')
    # ### end Alembic commands ###
