"""Add ContractorAssignment table

Revision ID: a8444619768f
Revises: 08e436854ca9
Create Date: 2025-07-27 11:10:55.510027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8444619768f'
down_revision = '08e436854ca9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contractor_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('contractor_company_id', sa.Integer(), nullable=False),
    sa.Column('is_preferred', sa.Boolean(), nullable=True),
    sa.Column('allow_doc_sharing', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('assigned_by_user_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['contractor_company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client_compliance_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_status', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_compliance_documents', schema=None) as batch_op:
        batch_op.drop_column('ai_status')

    op.drop_table('contractor_assignments')
    # ### end Alembic commands ###
