"""Add payment_run_id and finance_batch_id to Invoice model

Revision ID: ad423178f9b3
Revises: 30ac4ab32714
Create Date: 2025-07-21 08:44:11.985711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad423178f9b3'
down_revision = '30ac4ab32714'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_run_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_invoice_finance_batch', type_='foreignkey')
        batch_op.create_foreign_key('fk_invoice_payment_run', 'payment_runs', ['payment_run_id'], ['id'], initially='DEFERRED', deferrable=True, use_alter=True)
        batch_op.create_foreign_key('fk_invoice_finance_batch', 'finance_batches', ['finance_batch_id'], ['id'], initially='DEFERRED', deferrable=True, use_alter=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_constraint('fk_invoice_finance_batch', type_='foreignkey')
        batch_op.drop_constraint('fk_invoice_payment_run', type_='foreignkey')
        batch_op.create_foreign_key('fk_invoice_finance_batch', 'payment_runs', ['finance_batch_id'], ['id'], initially='DEFERRED', deferrable=True)
        batch_op.drop_column('payment_run_id')

    # ### end Alembic commands ###
