"""Fix ambiguous foreign key on Invoice

Revision ID: af6d16f9f025
Revises: c36c6db10b9b
Create Date: 2025-06-19 23:35:44.564442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af6d16f9f025'
down_revision = 'c36c6db10b9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pin', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_active')
        batch_op.drop_column('pin')

    # ### end Alembic commands ###
