"""Add Refund model

Revision ID: b206822afa27
Revises: 726cf2034f42
Create Date: 2025-07-13 19:56:57.230950

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b206822afa27'
down_revision = '726cf2034f42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refunds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('original_payment_id', sa.Integer(), nullable=True),
    sa.Column('reconciliation_batch_id', sa.Integer(), nullable=True),
    sa.Column('refund_reason', sa.String(length=255), nullable=False),
    sa.Column('refund_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('refund_method', sa.String(length=100), nullable=False),
    sa.Column('refund_reference', sa.String(length=100), nullable=True),
    sa.Column('refunded_to', sa.String(length=255), nullable=True),
    sa.Column('refund_status', sa.String(length=50), nullable=True),
    sa.Column('is_finalised', sa.Boolean(), nullable=True),
    sa.Column('is_reconciled', sa.Boolean(), nullable=True),
    sa.Column('ai_validated', sa.Boolean(), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('ai_notes', sa.Text(), nullable=True),
    sa.Column('parsed_summary', sa.Text(), nullable=True),
    sa.Column('extracted_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('smart_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('gar_flagged', sa.Boolean(), nullable=True),
    sa.Column('gar_reason', sa.Text(), nullable=True),
    sa.Column('gar_score', sa.String(length=20), nullable=True),
    sa.Column('approved_by_gar', sa.Boolean(), nullable=True),
    sa.Column('gar_chat_ready', sa.Boolean(), nullable=True),
    sa.Column('gar_feedback', sa.Text(), nullable=True),
    sa.Column('issued_by_id', sa.Integer(), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['issued_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['original_payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['reconciliation_batch_id'], ['reconciliation_batches.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refunds')
    # ### end Alembic commands ###
