"""Update Unit model with AI, GAR, financial, and ownership enhancements

Revision ID: b605cc407504
Revises: f6d8f37f849b
Create Date: 2025-07-15 15:15:43.358823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b605cc407504'
down_revision = 'f6d8f37f849b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_occupied', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('last_inspection_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('service_charge_amount', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('billing_frequency', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('financial_account_ref', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('gar_risk_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('gar_alignment_status', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('client_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.alter_column('client_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('gar_alignment_status')
        batch_op.drop_column('gar_risk_score')
        batch_op.drop_column('financial_account_ref')
        batch_op.drop_column('billing_frequency')
        batch_op.drop_column('service_charge_amount')
        batch_op.drop_column('last_inspection_date')
        batch_op.drop_column('is_occupied')

    # ### end Alembic commands ###
