"""Client: addr1/addr2/city, units breakdown, FYE text, assignments, client_code

Revision ID: b9f87d649c8d
Revises: b964ebe30315
Create Date: 2025-09-03 21:21:24.668055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9f87d649c8d'
down_revision = 'b964ebe30315'
branch_labels = None
depends_on = None


def upgrade():
    # 1) Add new columns + a temp FYE text column
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address_line1', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('address_line2', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('units_apartments', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('units_houses', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('units_duplexes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('units_commercial', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('assigned_fc_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('assigned_assistant_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('client_code', sa.String(length=50), nullable=True))

        # instead of altering the existing column type directly, add a temp text column
        batch_op.add_column(sa.Column('financial_year_end_text', sa.String(length=5), nullable=True))

    # 2) Backfill the temp FYE column from the existing DATE column → "DD/MM"
    # (PostgreSQL-safe; if your old column was DATE this covers all rows)
    op.execute("""
        UPDATE clients
           SET financial_year_end_text = to_char(financial_year_end::date, 'DD/MM')
         WHERE financial_year_end IS NOT NULL
    """)

    # 3) Drop old FYE column and rename the temp one to final name; then create indexes + FKs
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('financial_year_end')
        batch_op.alter_column(
            'financial_year_end_text',
            new_column_name='financial_year_end',
            existing_type=sa.String(length=5),
            type_=sa.String(length=5),
            existing_nullable=True,
            nullable=True
        )

        # indexes / constraints (kept exactly as you had them)
        batch_op.create_index(batch_op.f('ix_clients_assigned_assistant_id'), ['assigned_assistant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clients_assigned_fc_id'), ['assigned_fc_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clients_client_code'), ['client_code'], unique=True)
        batch_op.create_foreign_key(None, 'users', ['assigned_fc_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['assigned_assistant_id'], ['id'])


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_clients_client_code'))
        batch_op.drop_index(batch_op.f('ix_clients_assigned_fc_id'))
        batch_op.drop_index(batch_op.f('ix_clients_assigned_assistant_id'))
        batch_op.alter_column('financial_year_end',
               existing_type=sa.String(length=5),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.drop_column('client_code')
        batch_op.drop_column('assigned_assistant_id')
        batch_op.drop_column('assigned_fc_id')
        batch_op.drop_column('units_commercial')
        batch_op.drop_column('units_duplexes')
        batch_op.drop_column('units_houses')
        batch_op.drop_column('units_apartments')
        batch_op.drop_column('city')
        batch_op.drop_column('address_line2')
        batch_op.drop_column('address_line1')

    # ### end Alembic commands ###
