"""Add QuoteRecipient Table

Revision ID: ba32fa96b9c5
Revises: 947d845a5091
Create Date: 2025-07-15 20:46:10.049710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba32fa96b9c5'
down_revision = '947d845a5091'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quote_recipients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_order_id', sa.Integer(), nullable=False),
    sa.Column('contractor_id', sa.Integer(), nullable=False),
    sa.Column('invited_by_id', sa.Integer(), nullable=True),
    sa.Column('invited_at', sa.DateTime(), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('contractor_viewed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('response_status', sa.String(length=50), nullable=True),
    sa.Column('contractor_viewed', sa.Boolean(), nullable=True),
    sa.Column('has_submitted_response', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('invitation_message', sa.Text(), nullable=True),
    sa.Column('decision_feedback', sa.Text(), nullable=True),
    sa.Column('notification_sent', sa.Boolean(), nullable=True),
    sa.Column('notification_sent_at', sa.DateTime(), nullable=True),
    sa.Column('reminder_sent', sa.Boolean(), nullable=True),
    sa.Column('reminder_sent_at', sa.DateTime(), nullable=True),
    sa.Column('visibility_scope', sa.String(length=50), nullable=True),
    sa.Column('visible_to_directors', sa.Boolean(), nullable=True),
    sa.Column('visible_to_contractor', sa.Boolean(), nullable=True),
    sa.Column('archived_by_admin', sa.Boolean(), nullable=True),
    sa.Column('auto_generated', sa.Boolean(), nullable=True),
    sa.Column('selection_rank', sa.Integer(), nullable=True),
    sa.Column('ai_suitability_score', sa.Float(), nullable=True),
    sa.Column('gar_visible', sa.Boolean(), nullable=True),
    sa.Column('gar_flagged', sa.Boolean(), nullable=True),
    sa.Column('gar_feedback', sa.Text(), nullable=True),
    sa.Column('gar_reason_excluded', sa.Text(), nullable=True),
    sa.Column('gar_alignment_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['contractor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['invited_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quote_recipients')
    # ### end Alembic commands ###
