"""Add LoanDocument model

Revision ID: c7830243c89d
Revises: c1a05678bda1
Create Date: 2025-07-14 21:42:09.708429

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c7830243c89d'
down_revision = 'c1a05678bda1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loan_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('file_path', sa.String(length=300), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('is_expired', sa.Boolean(), nullable=True),
    sa.Column('version_number', sa.String(length=20), nullable=True),
    sa.Column('previous_version_id', sa.Integer(), nullable=True),
    sa.Column('external_storage_id', sa.String(length=255), nullable=True),
    sa.Column('storage_provider', sa.String(length=100), nullable=True),
    sa.Column('download_token', sa.String(length=255), nullable=True),
    sa.Column('parsed_summary', sa.Text(), nullable=True),
    sa.Column('ai_tags', sa.Text(), nullable=True),
    sa.Column('gar_risk_flag', sa.Boolean(), nullable=True),
    sa.Column('gar_context_reference', sa.String(length=100), nullable=True),
    sa.Column('gar_notes', sa.Text(), nullable=True),
    sa.Column('extracted_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_modified_at', sa.DateTime(), nullable=True),
    sa.Column('last_modified_by_id', sa.Integer(), nullable=True),
    sa.Column('ip_uploaded_from', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['last_modified_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.ForeignKeyConstraint(['previous_version_id'], ['loan_documents.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loan_documents')
    # ### end Alembic commands ###
