"""Add SupplierPaymentReconciliation table

Revision ID: c8de13b1b5a0
Revises: 7c9d2eb13989
Create Date: 2025-07-14 21:19:17.915172

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c8de13b1b5a0'
down_revision = '7c9d2eb13989'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier_payment_reconciliations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('reconciled_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('discrepancy_reason', sa.Text(), nullable=True),
    sa.Column('reconciliation_batch_id', sa.Integer(), nullable=True),
    sa.Column('reconciled_at', sa.DateTime(), nullable=True),
    sa.Column('reconciled_by_id', sa.Integer(), nullable=True),
    sa.Column('ai_flagged', sa.Boolean(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('gar_score', sa.Float(), nullable=True),
    sa.Column('gar_notes', sa.Text(), nullable=True),
    sa.Column('gar_justification', sa.Text(), nullable=True),
    sa.Column('approved_by_gar', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['outstanding_supplier_invoices.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['reconciled_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reconciliation_batch_id'], ['reconciliation_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supplier_payment_reconciliations')
    # ### end Alembic commands ###
