"""Add BudgetForecast table

Revision ID: d5beb2b33f3d
Revises: 1221d2a92dde
Create Date: 2025-07-14 09:00:40.250289

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd5beb2b33f3d'
down_revision = '1221d2a92dde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget_forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.String(length=9), nullable=False),
    sa.Column('forecast_date', sa.Date(), nullable=True),
    sa.Column('forecast_period', sa.String(length=50), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=150), nullable=False),
    sa.Column('forecast_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('adjustment_reason', sa.Text(), nullable=True),
    sa.Column('ai_projection', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('gar_risk_flag', sa.Boolean(), nullable=True),
    sa.Column('ai_trend_summary', sa.Text(), nullable=True),
    sa.Column('gar_recommendation', sa.Text(), nullable=True),
    sa.Column('gar_context_reference', sa.String(length=255), nullable=True),
    sa.Column('forecast_notes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_scorecard', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('gar_chat_ready', sa.Boolean(), nullable=True),
    sa.Column('gar_feedback', sa.Text(), nullable=True),
    sa.Column('external_reference', sa.String(length=100), nullable=True),
    sa.Column('sync_status', sa.String(length=50), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('visibility_roles', sa.ARRAY(sa.String(length=50)), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('budget_forecasts')
    # ### end Alembic commands ###
