"""Add agm_completed field to clients

Revision ID: d8ae8edcef5a
Revises: 9933d997a639
Create Date: 2025-06-25 08:57:11.789737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8ae8edcef5a'
down_revision = '9933d997a639'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agm_completed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('agm_completed')

    # ### end Alembic commands ###
