"""Add bank_accounts table

Revision ID: e17b5bf74b25
Revises: 4e93569aa155
Create Date: 2025-07-13 13:15:38.841082

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e17b5bf74b25'
down_revision = '4e93569aa155'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('account_type', sa.String(length=50), nullable=False),
    sa.Column('account_name', sa.String(length=100), nullable=False),
    sa.Column('account_number_masked', sa.String(length=50), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('iban', sa.String(length=50), nullable=True),
    sa.Column('bic', sa.String(length=20), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('opening_balance', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('current_balance', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('is_live_linked', sa.Boolean(), nullable=True),
    sa.Column('banking_provider', sa.String(length=100), nullable=True),
    sa.Column('sync_status', sa.String(length=50), nullable=True),
    sa.Column('encryption_reference', sa.String(length=255), nullable=True),
    sa.Column('access_revoked', sa.Boolean(), nullable=True),
    sa.Column('audit_consent_reference', sa.String(length=255), nullable=True),
    sa.Column('gar_context_reference', sa.String(length=100), nullable=True),
    sa.Column('flagged_by_gar', sa.Boolean(), nullable=True),
    sa.Column('gar_notes', sa.Text(), nullable=True),
    sa.Column('parsed_summary', sa.Text(), nullable=True),
    sa.Column('extracted_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_risk_score', sa.Float(), nullable=True),
    sa.Column('ai_recommendation', sa.Text(), nullable=True),
    sa.Column('is_gar_verified', sa.Boolean(), nullable=True),
    sa.Column('gar_chat_ready', sa.Boolean(), nullable=True),
    sa.Column('gar_feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bank_accounts')
    # ### end Alembic commands ###
