"""Add CashFlowStatement table

Revision ID: e571f2a72acd
Revises: 12aa7c63df29
Create Date: 2025-07-14 08:52:49.792513

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e571f2a72acd'
down_revision = '12aa7c63df29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cashflow_statements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('operating_activities', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('investing_activities', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('financing_activities', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('net_cash_flow', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('breakdown_operating', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('breakdown_investing', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('breakdown_financing', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parsed_text', sa.Text(), nullable=True),
    sa.Column('extracted_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_scorecard', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('gar_insights', sa.Text(), nullable=True),
    sa.Column('gar_recommendation', sa.String(length=255), nullable=True),
    sa.Column('gar_context_reference', sa.String(length=255), nullable=True),
    sa.Column('flagged_by_gar', sa.Boolean(), nullable=True),
    sa.Column('context_tags', sa.ARRAY(sa.String(length=50)), nullable=True),
    sa.Column('role_visibility', sa.ARRAY(sa.String(length=50)), nullable=True),
    sa.Column('gar_chat_ready', sa.Boolean(), nullable=True),
    sa.Column('gar_feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cashflow_statements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cashflow_statements_report_date'), ['report_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cashflow_statements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cashflow_statements_report_date'))

    op.drop_table('cashflow_statements')
    # ### end Alembic commands ###
