"""create enhanced tenancies table

Revision ID: ea702c994c82
Revises: ab9176a636b4
Create Date: 2025-07-11 14:16:50.399369

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ea702c994c82'
down_revision = 'ab9176a636b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenancies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('resident_id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('lease_start_date', sa.Date(), nullable=False),
    sa.Column('lease_end_date', sa.Date(), nullable=True),
    sa.Column('break_clause_date', sa.Date(), nullable=True),
    sa.Column('rent_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('service_charge', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('payment_frequency', sa.String(length=50), nullable=True),
    sa.Column('rent_currency', sa.String(length=10), nullable=True),
    sa.Column('is_data_encrypted', sa.Boolean(), nullable=True),
    sa.Column('is_gdpr_consented', sa.Boolean(), nullable=True),
    sa.Column('gdpr_consent_date', sa.Date(), nullable=True),
    sa.Column('lease_document_url', sa.String(length=255), nullable=True),
    sa.Column('external_property_ref', sa.String(length=100), nullable=True),
    sa.Column('external_lease_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('termination_reason', sa.String(length=255), nullable=True),
    sa.Column('auto_renew', sa.Boolean(), nullable=True),
    sa.Column('parsed_summary', sa.Text(), nullable=True),
    sa.Column('parsed_text', sa.Text(), nullable=True),
    sa.Column('extracted_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('gar_recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resident_id'], ['residents.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tenancies')
    # ### end Alembic commands ###
