"""Add TeamMessage table

Revision ID: ea71243d4dc7
Revises: 6ba04501f1e0
Create Date: 2025-07-19 08:29:22.634901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea71243d4dc7'
down_revision = '6ba04501f1e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contractor_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('recipient_user_id', sa.Integer(), nullable=True),
    sa.Column('message_body', sa.Text(), nullable=False),
    sa.Column('is_urgent', sa.Boolean(), nullable=True),
    sa.Column('attachment_url', sa.String(length=255), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('parsed_summary', sa.Text(), nullable=True),
    sa.Column('extracted_data', sa.JSON(), nullable=True),
    sa.Column('parsing_status', sa.String(length=50), nullable=True),
    sa.Column('parsed_by_ai_version', sa.String(length=50), nullable=True),
    sa.Column('parsed_at', sa.DateTime(), nullable=True),
    sa.Column('gar_sensitivity_flag', sa.Boolean(), nullable=True),
    sa.Column('gar_communication_risk', sa.Text(), nullable=True),
    sa.Column('gar_chat_ready', sa.Boolean(), nullable=True),
    sa.Column('gar_feedback', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], ),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['contractor_teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('work_order_completions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_team_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('completion_type', sa.String(length=50), nullable=True))
        batch_op.create_foreign_key(None, 'contractor_teams', ['assigned_team_id'], ['id'])

    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('assigned_team_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'contractor_teams', ['assigned_team_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['assigned_user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('assigned_team_id')
        batch_op.drop_column('assigned_user_id')

    with op.batch_alter_table('work_order_completions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('completion_type')
        batch_op.drop_column('assigned_team_id')

    op.drop_table('team_messages')
    # ### end Alembic commands ###
