"""Add HRSettingEntry Table

Revision ID: eac11b433734
Revises: 82f7e9b622da
Create Date: 2025-07-15 21:58:27.856802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eac11b433734'
down_revision = '82f7e9b622da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hr_visibility_controls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('viewer_role', sa.String(length=100), nullable=False),
    sa.Column('viewer_user_id', sa.Integer(), nullable=True),
    sa.Column('module', sa.String(length=100), nullable=False),
    sa.Column('field', sa.String(length=100), nullable=True),
    sa.Column('access_level', sa.String(length=50), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['viewer_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hr_visibility_controls')
    # ### end Alembic commands ###
