"""Add MeetingIntergration Table

Revision ID: f6d8f37f849b
Revises: 9086c840c85a
Create Date: 2025-07-15 13:27:00.377953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6d8f37f849b'
down_revision = '9086c840c85a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting_integrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('board_meeting_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('meeting_url', sa.String(length=500), nullable=False),
    sa.Column('join_link', sa.String(length=500), nullable=True),
    sa.Column('dial_in_number', sa.String(length=100), nullable=True),
    sa.Column('meeting_id', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('api_integration_id', sa.String(length=100), nullable=True),
    sa.Column('oauth_token', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_recording_enabled', sa.Boolean(), nullable=True),
    sa.Column('recording_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['board_meeting_id'], ['board_meetings.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meeting_integrations')
    # ### end Alembic commands ###
