"""Fix circular dependencies in User model using deferrable foreign keys

Revision ID: f70ca224fde0
Revises: 14129806d28c
Create Date: 2025-07-15 21:27:42.027293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f70ca224fde0'
down_revision = '14129806d28c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_company_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('users_role_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('users_contractor_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key('fk_user_role', 'roles', ['role_id'], ['id'], initially='DEFERRED', deferrable=True, use_alter=True)
        batch_op.create_foreign_key('fk_user_contractor', 'contractors', ['contractor_id'], ['id'], initially='DEFERRED', deferrable=True, use_alter=True)
        batch_op.create_foreign_key('fk_user_client', 'clients', ['company_id'], ['id'], initially='DEFERRED', deferrable=True, use_alter=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_client', type_='foreignkey')
        batch_op.drop_constraint('fk_user_contractor', type_='foreignkey')
        batch_op.drop_constraint('fk_user_role', type_='foreignkey')
        batch_op.create_foreign_key('users_contractor_id_fkey', 'contractors', ['contractor_id'], ['id'])
        batch_op.create_foreign_key('users_role_id_fkey', 'roles', ['role_id'], ['id'])
        batch_op.create_foreign_key('users_company_id_fkey', 'clients', ['company_id'], ['id'])

    # ### end Alembic commands ###
