"""Validate that architecture, manual and stabilisation documents stay discoverable.

This is intentionally small: it protects the documentation entry points that
keep LogixPM understandable as the module ecosystem grows.
"""

from __future__ import annotations

from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]


REQUIRED_FILES = (
    "README.md",
    "docs/platform_architecture.md",
    "docs/platform_stabilisation_register.md",
    "docs/stabilisation_security_closeout.md",
    "docs/module_access_matrix.md",
    "docs/module_connection_matrix.md",
    "docs/document_template_ownership_matrix.md",
    "docs/source_record_identity_matrix.md",
    "docs/external_integration_security_matrix.md",
    "docs/deployment_environment_security_matrix.md",
    "docs/incident_response_backup_matrix.md",
    "docs/privacy_data_classification_matrix.md",
    "docs/observability_monitoring_matrix.md",
    "docs/release_change_management_matrix.md",
    "docs/production_readiness_gate.md",
    "docs/support_escalation_ownership_matrix.md",
    "docs/onboarding_data_import_matrix.md",
    "docs/gar_visibility_matrix.md",
    "docs/auditability_matrix.md",
    "docs/data_retention_deletion_matrix.md",
    "docs/module_completion_register.md",
    "docs/role_dashboard_surface_standard.md",
    "docs/module_contracts.md",
    "docs/manual/index.md",
)

REQUIRED_REFERENCES = {
    "README.md": (
        "docs/platform_architecture.md",
        "docs/platform_stabilisation_register.md",
        "docs/stabilisation_security_closeout.md",
        "docs/module_access_matrix.md",
        "docs/module_connection_matrix.md",
        "docs/document_template_ownership_matrix.md",
        "docs/source_record_identity_matrix.md",
        "docs/external_integration_security_matrix.md",
        "docs/deployment_environment_security_matrix.md",
        "docs/incident_response_backup_matrix.md",
        "docs/privacy_data_classification_matrix.md",
        "docs/observability_monitoring_matrix.md",
        "docs/release_change_management_matrix.md",
        "docs/production_readiness_gate.md",
        "docs/support_escalation_ownership_matrix.md",
        "docs/onboarding_data_import_matrix.md",
        "docs/gar_visibility_matrix.md",
        "docs/auditability_matrix.md",
        "docs/data_retention_deletion_matrix.md",
        "docs/module_completion_register.md",
        "docs/role_dashboard_surface_standard.md",
        "docs/module_contracts.md",
        "docs/manual/index.md",
        "phase3_readiness_check.py --quick",
        "platform_documentation_contract_check.py",
    ),
    "docs/manual/index.md": (
        "Architecture And Governance Notes",
        "docs/platform_architecture.md",
        "docs/platform_stabilisation_register.md",
        "docs/module_completion_register.md",
        "docs/role_dashboard_surface_standard.md",
        "docs/module_contracts.md",
        "platform_documentation_contract_check.py",
        "stabilisation_register_gate_check.py",
        "module_service_contract_check.py",
        "app_module_settings_feed_contract_check.py",
        "admin_portal_access_contract_check.py",
    ),
    "docs/platform_architecture.md": (
        "Related Control Documents",
        "docs/platform_stabilisation_register.md",
        "docs/module_completion_register.md",
        "docs/role_dashboard_surface_standard.md",
        "docs/module_contracts.md",
        "docs/manual/index.md",
        "phase3_readiness_check.py --quick",
        "phase3_readiness_check.py --smoke-only",
        "phase3_runner_contract_check.py",
        "platform_documentation_contract_check.py",
        "stabilisation_register_gate_check.py",
        "module_completion_register_check.py",
        "module_settings_registry_check.py",
        "legacy_archive_isolation_check.py",
        "media_evidence_spine_check.py",
        "contractor_document_template_boundary_check.py",
        "organisation_connection_boundary_check.py",
        "module_service_contract_check.py",
        "app_module_settings_feed_contract_check.py",
        "admin_portal_access_contract_check.py",
    ),
    "docs/platform_stabilisation_register.md": (
        "Close-Out Status",
        "Finance Logix security/stabilisation is intentionally deferred",
        "docs/stabilisation_security_closeout.md",
        "docs/module_access_matrix.md",
        "docs/module_connection_matrix.md",
        "docs/document_template_ownership_matrix.md",
        "docs/source_record_identity_matrix.md",
        "docs/external_integration_security_matrix.md",
        "docs/deployment_environment_security_matrix.md",
        "docs/incident_response_backup_matrix.md",
        "docs/privacy_data_classification_matrix.md",
        "docs/observability_monitoring_matrix.md",
        "docs/release_change_management_matrix.md",
        "docs/production_readiness_gate.md",
        "docs/support_escalation_ownership_matrix.md",
        "docs/onboarding_data_import_matrix.md",
        "docs/gar_visibility_matrix.md",
        "docs/auditability_matrix.md",
        "docs/data_retention_deletion_matrix.md",
        "Non-Negotiable Build Rules",
        "Verification Gates",
        "docs/module_completion_register.md",
        "phase3_readiness_check.py --quick",
        "phase3_readiness_check.py --smoke-only",
        "phase3_runner_contract_check.py",
        "platform_documentation_contract_check.py",
        "stabilisation_register_gate_check.py",
        "module_completion_register_check.py",
        "module_access_security_boundary_check.py",
        "module_settings_registry_check.py",
        "legacy_archive_isolation_check.py",
        "media_evidence_spine_check.py",
        "contractor_document_template_boundary_check.py",
        "organisation_connection_boundary_check.py",
        "module_service_contract_check.py",
        "app_module_settings_feed_contract_check.py",
        "admin_portal_access_contract_check.py",
    ),
    "docs/stabilisation_security_closeout.md": (
        "Stabilisation and Security Close-Out",
        "docs/module_access_matrix.md",
        "docs/module_connection_matrix.md",
        "docs/document_template_ownership_matrix.md",
        "docs/source_record_identity_matrix.md",
        "docs/external_integration_security_matrix.md",
        "docs/deployment_environment_security_matrix.md",
        "docs/incident_response_backup_matrix.md",
        "docs/privacy_data_classification_matrix.md",
        "docs/observability_monitoring_matrix.md",
        "docs/release_change_management_matrix.md",
        "docs/production_readiness_gate.md",
        "docs/support_escalation_ownership_matrix.md",
        "docs/onboarding_data_import_matrix.md",
        "docs/gar_visibility_matrix.md",
        "docs/auditability_matrix.md",
        "docs/data_retention_deletion_matrix.md",
        "Current Close-Out Position",
        "Release Readiness Rules",
        "Module Expansion Checklist",
        "Red Flags",
        "Finance Logix is deliberately treated as a separate module-owned security slice",
        "Contractor Logix must not become accessible to property management company users",
        "organisation connections must use governed organisation identity",
        "source IDs, stable UIDs and safe human-readable references",
        "external integrations must be owned by the module that uses them",
        "deployment configuration must keep secrets",
        "backup, restore and incident response must preserve source records",
        "personal, financial, HR, contractor-private and security/access data must be classified",
        "dashboard counts, health feeds, operational alerts and degraded states must be source-backed",
        "release changes must be scoped, validated, rollback-aware",
        "production readiness must be explicit",
        "support ownership and escalation must follow the module",
        "onboarding and imports must be batch-aware",
        "GAR must read source-backed records with role and visibility controls",
        "cross-module actions must record module ownership",
        "deletion must default to archive",
        "phase3_readiness_check.py --quick",
        "platform_documentation_contract_check.py",
        "module_access_security_boundary_check.py",
        "module_settings_registry_check.py",
        "contractor_document_template_boundary_check.py",
        "organisation_connection_boundary_check.py",
        "legacy_archive_isolation_check.py",
    ),
    "docs/module_connection_matrix.md": (
        "Module Connection Matrix",
        "Core Rule",
        "Platform Identity",
        "Internal Module Connections",
        "Standalone Module Rule",
        "External Integrations",
        "docs/external_integration_security_matrix.md",
        "Connection Lifecycle",
        "Do not use email addresses as the primary cross-organisation link",
        "Contractor Logix can create standalone job dockets without a linked Works Logix work order",
        "Finance owns credentials, mapping, sync logs and posting controls",
        "GAR may draft structured records, but a human or workflow rule must approve creation",
        "organisation_connection_boundary_check.py",
        "module_access_security_boundary_check.py",
        "module_service_contract_check.py",
        "gar_source_adapter_contract_check.py",
    ),
    "docs/document_template_ownership_matrix.md": (
        "Document Template Ownership Matrix",
        "Core Rule",
        "Ownership Matrix",
        "Numbering Rules",
        "Settings Placement",
        "The module that creates and controls the business document owns that document template",
        "Work-order numbers belong to Works Logix / Property Management Logix",
        "Job-docket numbers belong to Contractor Logix",
        "Contractor Logix settings for job dockets, contractor quotation responses, contractor payment requests and contractor completion reports",
        "Finance Logix settings for invoices, payment runs, statements, balance notices and finance reports",
        "a contractor setting edits a work-order template",
        "a LogixPM setting edits a contractor job-docket template",
        "contractor_document_template_boundary_check.py",
        "module_settings_registry_check.py",
        "module_access_security_boundary_check.py",
        "module_service_contract_check.py",
    ),
    "docs/source_record_identity_matrix.md": (
        "Source Record Identity Matrix",
        "Core Rule",
        "Identity Types",
        "Record Identity Matrix",
        "Reference Display Rules",
        "Cross-Module Linking Rules",
        "Use source IDs and stable UIDs for system links",
        "Do not use email addresses, display names, short work-order numbers or document labels as the primary cross-module link",
        "Work order",
        "Job docket",
        "Contractor job number",
        "GAR may cite human references, but must store source record references",
        "a work-order number can collide across two management companies without source context",
        "platform_documentation_contract_check.py",
        "module_service_contract_check.py",
        "organisation_connection_boundary_check.py",
        "gar_source_adapter_contract_check.py",
    ),
    "docs/external_integration_security_matrix.md": (
        "External Integration Security Matrix",
        "Core Rule",
        "Credential Ownership Matrix",
        "Sync And Scope Rules",
        "External Intake Rules",
        "Revocation And Audit Rules",
        "The module that uses an external integration owns the credentials",
        "Shared platform services may provide encryption",
        "Accounting package",
        "HR platform",
        "Contractor calendar",
        "Email intake",
        "Cloud document storage",
        "AI provider",
        "GAR or an intake parser may draft structured records",
        "one module uses another module's external credential",
        "external sync overwrites a finalised, approved, signed or closed Logix record",
        "platform_documentation_contract_check.py",
        "module_settings_registry_check.py",
        "module_service_contract_check.py",
        "organisation_connection_boundary_check.py",
        "gar_source_adapter_contract_check.py",
    ),
    "docs/deployment_environment_security_matrix.md": (
        "Deployment Environment Security Matrix",
        "Core Rule",
        "Environment Ownership Matrix",
        "Production Safety Rules",
        "Module Deployment Rules",
        "Seed And Test Data Rules",
        "Release Readiness Questions",
        "Production configuration must be explicit, module-aware and environment-owned",
        "Do not rely on local defaults, seeded test users, debug behaviour",
        "Production must not run with debug mode enabled",
        "Seed scripts must be safe to run locally",
        "Feature flags and module subscriptions must gate module routes",
        "Finance Logix",
        "Contractor Logix",
        "GAR AI Layer",
        "production uses a local development secret key",
        "a seed script creates privileged users in production",
        "platform_documentation_contract_check.py",
        "migration_integrity_check.py",
        "module_access_security_boundary_check.py",
        "module_settings_registry_check.py",
        "app_module_settings_feed_contract_check.py",
        "phase3_runner_contract_check.py",
    ),
    "docs/incident_response_backup_matrix.md": (
        "Incident Response and Backup Matrix",
        "Core Rule",
        "Backup Ownership Matrix",
        "Recovery Rules",
        "Incident Response Workflow",
        "Module Incident Examples",
        "Every module must know how its source records",
        "Restores must preserve source references",
        "Production recovery must not use local development data",
        "Media and evidence storage must be restored",
        "External sync tokens, cursors and webhook positions must be reviewed",
        "GAR indexes, summaries or cached answers must be treated as derived data",
        "a restore overwrites a signed, approved, completed, paid or closed record",
        "a backup excludes media, photos, videos or evidence",
        "an incident is fixed by deleting audit logs or source history",
        "platform_documentation_contract_check.py",
        "archive_inventory_check.py --strict",
        "legacy_archive_isolation_check.py",
        "migration_integrity_check.py",
        "media_evidence_spine_check.py",
        "works_evidence_audit_contract_check.py",
        "phase3_runner_contract_check.py",
    ),
    "docs/privacy_data_classification_matrix.md": (
        "Privacy and Data Classification Matrix",
        "Core Rule",
        "Data Classification Levels",
        "Module Handling Matrix",
        "Privacy Rules",
        "Export, Notification and AI Rules",
        "Every field, document, media item, feed and GAR source must have a clear data classification",
        "Access to a module does not automatically mean access to every data class",
        "Personal Data",
        "Sensitive Personal Data",
        "Financial Data",
        "Contractor Private",
        "Security / Access",
        "Derived AI Data",
        "Contractors may receive reporter contact details only where needed",
        "Contractor private materials, time logs and internal notes must not be shown",
        "Finance data must not be copied into general dashboards",
        "HR data must stay in HR Logix",
        "GAR must not infer or expose personal, financial, HR or contractor-private details",
        "platform_documentation_contract_check.py",
        "module_access_security_boundary_check.py",
        "gar_role_visibility_contract_check.py",
        "gar_source_adapter_contract_check.py",
        "notification_role_visibility_contract_check.py",
        "works_access_control_check.py",
        "phase3_runner_contract_check.py",
    ),
    "docs/observability_monitoring_matrix.md": (
        "Observability and Monitoring Matrix",
        "Core Rule",
        "Signal Ownership Matrix",
        "Monitoring Rules",
        "Degraded State Rules",
        "GAR Monitoring Rules",
        "Alerting Rules",
        "Every module must expose enough operational signals",
        "Monitoring is not a substitute for audit history",
        "Queue counts must match the records behind the tile",
        "Error logs must not include passwords, API keys, portal invite codes",
        "GAR source adapters must report degraded or unavailable states",
        "External integration sync jobs must expose last successful sync",
        "Media/evidence upload failures must be visible",
        "a dashboard count cannot be traced to the source query behind it",
        "GAR answers while its required source adapter is failing or stale",
        "external sync failures are visible only in server logs",
        "platform_documentation_contract_check.py",
        "app_health_feed_contract_check.py",
        "app_feed_contract_check.py",
        "role_dashboard_surface_check.py",
        "queue_surface_contract_check.py",
        "gar_source_adapter_contract_check.py",
        "notification_contract_check.py",
        "phase3_runner_contract_check.py",
    ),
    "docs/release_change_management_matrix.md": (
        "Release and Change Management Matrix",
        "Core Rule",
        "Release Ownership Matrix",
        "Change Classes",
        "Release Rules",
        "PR And Merge Checklist",
        "Module Activation Rules",
        "Rollback And Recovery Rules",
        "Every code, schema, data, setting, document-template, external-integration and GAR change must have an owner",
        "Do not stage unrelated dirty files",
        "Do not activate a module because a route exists",
        "Do not promote local review users, demo records or seed scripts as production content",
        "Do not ship migrations without their matching model and route/service expectations",
        "Do not rewrite signed, approved, completed, paid or closed source records during release",
        "Finance Logix, HR Logix, Director Logix and future standalone modules must follow this same rule",
        "GAR summaries, caches and indexes as derived data",
        "a release includes unrelated module work because it was already dirty locally",
        "a module becomes visible because a route exists rather than because module subscription, role and settings ownership allow it",
        "migration_integrity_check.py",
        "module_access_security_boundary_check.py",
        "module_settings_registry_check.py",
        "module_service_contract_check.py",
        "app_module_settings_feed_contract_check.py",
        "archive_inventory_check.py --strict",
    ),
    "docs/production_readiness_gate.md": (
        "Production Readiness Gate",
        "Core Rule",
        "Readiness Levels",
        "Module Readiness Checklist",
        "Module-Specific Gates",
        "Production Blockers",
        "Pilot Rules",
        "Sign-Off Record",
        "Nothing is production-ready until the owning module can prove its access rules",
        "Prototype",
        "Review",
        "Pilot",
        "Production",
        "Deferred",
        "role access is declared and enforced",
        "module-owned settings exist",
        "document templates are owned by the module that creates the document",
        "dashboard tiles match the lists behind them",
        "seed/demo data is excluded from production activation",
        "Finance Logix",
        "HR Logix",
        "a user can enter another module or organisation through direct URL",
        "GAR can answer from data the user cannot open directly",
        "the user manual does not explain the workflow",
        "docs/module_completion_register.md",
        "module_access_security_boundary_check.py",
        "module_settings_registry_check.py",
        "module_completion_register_check.py",
        "queue_surface_contract_check.py",
        "gar_source_adapter_contract_check.py",
        "archive_inventory_check.py --strict",
    ),
    "docs/support_escalation_ownership_matrix.md": (
        "Support and Escalation Ownership Matrix",
        "Core Rule",
        "Support Ownership Matrix",
        "Support Intake Rules",
        "Escalation Rules",
        "Customer Response Rules",
        "Support Severity",
        "GAR Support Rules",
        "Every production or pilot module must have an owning support role",
        "Support ownership must follow module ownership",
        "Support must be linked to the source record where possible",
        "Contractor-only support must stay inside Contractor Logix",
        "Finance and HR support must not be handled through general module notes",
        "a user can access a module or organisation they should not be allowed to use",
        "GAR gives an answer that is stale, unsourced, role-inappropriate or inconsistent with the source record",
        "Do not send sensitive personal, financial, HR, contractor-private, access/security or GAR-derived data",
        "If GAR is wrong because source data is wrong, fix the source module record",
        "a pilot or production module has no named support owner",
        "a data exposure incident is treated as an ordinary UI bug",
        "module_access_security_boundary_check.py",
        "notification_role_visibility_contract_check.py",
        "works_evidence_audit_contract_check.py",
        "gar_source_adapter_contract_check.py",
        "app_health_feed_contract_check.py",
    ),
    "docs/onboarding_data_import_matrix.md": (
        "Onboarding and Data Import Matrix",
        "Core Rule",
        "Import Ownership Matrix",
        "Import Readiness Checklist",
        "Data Quality Rules",
        "Portal and Membership Onboarding",
        "Document and Media Onboarding",
        "External Data Migration",
        "No imported or onboarded data becomes operational until it has an owning module",
        "Do not key cross-module links off email address",
        "unit_uid",
        "organisation_uid",
        "Portal codes and invites must be tied to a membership",
        "GAR may assist parsing or summarising imports",
        "Finance Logix imports are deferred",
        "HR Logix imports are deferred",
        "batch id",
        "a bulk portal invite is sent before owner/resident records are validated",
        "platform_documentation_contract_check.py",
        "media_evidence_spine_check.py",
        "organisation_connection_boundary_check.py",
        "phase3_runner_contract_check.py",
    ),
    "docs/gar_visibility_matrix.md": (
        "GAR Visibility Matrix",
        "Core Rule",
        "Source-Backed Answer Rule",
        "Role Visibility Matrix",
        "Module Source Rules",
        "Recommendation Rule",
        "GAR may only answer from source records the current user is allowed to access",
        "If a user cannot open the underlying record through the relevant module, GAR must not reveal its details",
        "GAR may recommend an action, but workflow authority stays with the module",
        "GAR exposes contractor-private notes to PM/Admin/Member users",
        "GAR exposes owner finance data to residents",
        "gar_role_visibility_contract_check.py",
        "gar_source_adapter_contract_check.py",
        "gar_inquiry_endpoint_check.py",
        "module_access_security_boundary_check.py",
    ),
    "docs/auditability_matrix.md": (
        "Auditability Matrix",
        "Core Rule",
        "Required Audit Fields",
        "Module Audit Ownership",
        "Cross-Module Audit Rules",
        "Human Approval Rule",
        "Immutable / Controlled Amendment Rule",
        "Every business action that changes state",
        "The audit trail must link back to the source record",
        "GAR owns recommendation metadata; the module owns the action taken by a human or workflow rule",
        "Human approval is required before",
        "Completed or signed business records should not be edited in place",
        "a notification is treated as the audit trail",
        "platform_documentation_contract_check.py",
        "works_evidence_audit_contract_check.py",
        "gar_source_adapter_contract_check.py",
    ),
    "docs/data_retention_deletion_matrix.md": (
        "Data Retention and Deletion Matrix",
        "Core Rule",
        "Deletion Types",
        "Module Retention Rules",
        "Protected Records",
        "Active View Rule",
        "Restore Rule",
        "GAR Rule",
        "Default to archive, deactivate, supersede or controlled amendment for business records",
        "Permanent deletion should be limited to disposable drafts",
        "Do not hard delete without a formal retention/legal workflow",
        "Archive should remove noise from active dashboards without deleting history",
        "GAR should not treat an archived record as active operational work",
        "a delete action removes a record with source links",
        "active dashboard counts include archived records by default",
        "archive_inventory_check.py --strict",
        "legacy_archive_isolation_check.py",
    ),
    "docs/module_access_matrix.md": (
        "Module Access Matrix",
        "Core Rule",
        "Role Access Matrix",
        "Boundary Examples",
        "Settings Ownership",
        "A Property Manager can see a contractor's completion evidence through Works Logix, but cannot enter the contractor's dashboard",
        "A Contractor can see the site, unit, contact and evidence details needed for assigned work",
        "GAR can answer across modules only when the user already has access to the underlying source records",
        "Contractor Logix owns contractor profile, job docket, quotation response, payment request, calendar, bank, insurance and contractor document-template settings",
        "Finance Logix owns finance settings, finance document templates, bank/reconciliation setup and accounting integrations",
        "module_access_security_boundary_check.py",
        "module_settings_registry_check.py",
        "contractor_document_template_boundary_check.py",
        "organisation_connection_boundary_check.py",
        "gar_role_visibility_contract_check.py",
    ),
    "docs/module_completion_register.md": (
        "Unfinished Module Completion Register",
        "Module Completion Register",
        "Module access/security boundaries",
        "Module settings ownership",
        "Organisation identity and connections",
        "Document template ownership",
        "manual_coverage_check.py",
        "phase3_manual_contract_check.py",
        "platform_documentation_contract_check.py",
        "module_completion_register_check.py",
        "module_settings_registry_check.py",
        "legacy_archive_isolation_check.py",
        "media_evidence_spine_check.py",
        "contractor_document_template_boundary_check.py",
        "organisation_connection_boundary_check.py",
        "Contractor Logix",
        "Finance Logix",
        "GAR AI Layer",
    ),
    "docs/role_dashboard_surface_standard.md": (
        "Every primary dashboard should",
        "avoid long duplicated lists",
        "queue_surface_contract_check.py",
        "key_site_info_contract_check.py",
    ),
    "docs/module_contracts.md": (
        "Dependency Rule",
        "source-backed service or feed",
        "module_dependency_boundary_check.py",
        "module_service_contract_check.py",
    ),
}


def main() -> int:
    failures: list[str] = []

    for relative_path in REQUIRED_FILES:
        if not (PROJECT_ROOT / relative_path).exists():
            failures.append(f"Missing required documentation file: {relative_path}")

    for relative_path, required_phrases in REQUIRED_REFERENCES.items():
        path = PROJECT_ROOT / relative_path
        if not path.exists():
            continue

        content = path.read_text(encoding="utf-8")
        for phrase in required_phrases:
            if phrase not in content:
                failures.append(f"{relative_path} is missing: {phrase}")

    print("Platform documentation contract check")
    print(f"- Required files checked: {len(REQUIRED_FILES)}")
    print(f"- Document references checked: {sum(len(v) for v in REQUIRED_REFERENCES.values())}")

    if failures:
        print("\nFAILED")
        for failure in failures:
            print(f"- {failure}")
        return 1

    print("\nPASSED")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
